/*
-- Query: select * from materia
LIMIT 0, 1000

-- Date: 2026-02-02 09:21
*/
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (1,'CIBERSEGURIDAD WEB');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (2,'DESARROLLO SEGURO DEL SOFTWARE');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (3,'PLATAFORMAS DE DESARROLLO DE SOFTWARE');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (4,'ADMINISTRACION DE SISITEMAS');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (5,'EXPERIENCIA E INTERFAZ DE USUARIO');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (6,'PROYECTO DE APLICACION');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (7,'METODOLOGIAS DESARROLLO Y CALIDAD');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (8,'DIRECCION Y GESTION');
INSERT INTO `` (`ID_MATERIA`,`NOMBRE_MATERIA`) VALUES (9,'DESARROLLO WEB INTEGRAL');
