ID_PREGUNTA,ID_SUBTEMA_TOPICO,ID_ORIGEN,PREGUNTA,RUTA_ARCHIVO,RESPUESTA_B,RESPUESTA_C,RESPUESTA_D,RESPUESTA_CORRECTA,EXPLICACION,IMAGEN_PREGUNTA,ERRORES,ID_MATERIA,UNIDAD,RESPUESTA_A,IMAGEN_RESP_A,IMAGEN_RESP_B,IMAGEN_RESP_C,IMAGEN_RESP_D,IMAGEN_EXPLICA,RESPUESTA_E,IMAGEN_RESP_E,RESPUESTA_F,IMAGEN_RESP_F,RESPUESTA_G,IMAGEN_RESP_G,RESPUESTA_H,IMAGEN_RESP_H,RESPUESTA_I,IMAGEN_RESP_I
1,1,1,"¿Cuál de las siguientes opciones es una declaración válida de variable en Java?",NULL,"B.-double precio = 25.99;","C.-string nombre = "Java";","D.-booleano esValido = true;",B,NULL,NULL,NULL,NULL,NULL,"A.-int numero = "10";",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
2,1,1,"¿Cuál de los siguientes modificadores de acceso permite que una variable o método solo sea accesible dentro de la misma clase?",NULL,B.-protected,C.-private,D.-default,C,NULL,NULL,NULL,NULL,NULL,A.-public,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
3,1,1,"¿Qué palabra clave se usa para declarar una constante en Java?",NULL,B.-final,C.-static,D.-let,B,"En Java, la palabra clave "final" se usa para declarar constantes.",NULL,NULL,NULL,NULL,A.-const,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
4,1,1,"¿Cuál es el tipo de dato predeterminado para números decimales en Java?",NULL,B.-double,C.-int,D.-decimal,B,"El tipo de dato predeterminado para números decimales en Java es "double".",NULL,NULL,NULL,NULL,A.-float,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
5,1,1,"¿Qué operador se usa para comparar si dos valores son iguales en Java?",NULL,B.-=,C.-equals(),D.-!=,A,"El operador "==" se usa para comparar valores primitivos en Java. Para objetos, se usa equals().",NULL,NULL,NULL,NULL,A.-==,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
6,1,1,"¿Cuál de los siguientes no es un tipo de dato primitivo en Java?",NULL,B.-String,C.-double,D.-boolean,B,"String no es un tipo de dato primitivo, es una clase en Java.",NULL,NULL,NULL,NULL,A.-int,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
7,1,1,"¿Cómo se declara un array de enteros en Java?",NULL,"B.-array<int> = new int[5];","C.-int[] array = new int(5);","D.-array[] int = new int[5];",A,"La forma correcta de declarar un array en Java es "int array[] = new int[5];".",NULL,NULL,NULL,NULL,"A.-int array[] = new int[5];",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
8,1,1,"¿Cuál es el resultado de la operación 10 / 3 en Java si ambos son enteros?",NULL,B.-3,C.-4,D.-Error,B,"En Java, la división entre enteros devuelve un entero, por lo que 10 / 3 es 3.",NULL,NULL,NULL,NULL,A.-3.33,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
9,1,1,"¿Qué estructura se usa para manejar excepciones en Java?",NULL,B.-switch-case,C.-try-catch,D.-for-each,C,"El bloque try-catch se usa para manejar excepciones en Java.",NULL,NULL,NULL,NULL,A.-if-else,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
10,1,1,"¿Cuál de las siguientes opciones es un bucle en Java?",NULL,B.-foreach(),C.-do-while,D.-if-else,C,"do-while es un bucle en Java que se ejecuta al menos una vez antes de evaluar la condición.",NULL,NULL,NULL,NULL,A.-loop(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
11,1,1,"¿Cuál es la función principal de la palabra clave "this" en Java?",NULL,"B.-Referenciar la propia instancia de la clase","C.-Indicar una variable global","D.-Acceder a métodos estáticos",B,"La palabra clave "this" en Java se usa para referenciar la instancia actual de la clase.",NULL,NULL,NULL,NULL,"A.-Referenciar la superclase",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
12,1,1,"¿Qué palabra clave se usa para heredar una clase en Java?",NULL,B.-inherits,C.-extends,D.-override,C,"Para heredar una clase en Java se usa "extends".",NULL,NULL,NULL,NULL,A.-implements,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
13,1,1,"¿Qué modificador de acceso permite que un método sea accesible desde cualquier parte del programa?",NULL,B.-protected,C.-default,D.-public,D,"El modificador "public" permite que un método sea accesible desde cualquier parte del programa.",NULL,NULL,NULL,NULL,A.-private,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
14,1,1,"¿Qué pasa si un método tiene el mismo nombre pero diferente número de parámetros?",NULL,"B.-Sobrecarga de métodos","C.-Sobrescritura de métodos","D.-No es permitido en Java",B,"Se llama sobrecarga de métodos (method overloading), donde un método tiene el mismo nombre pero diferentes parámetros.",NULL,NULL,NULL,NULL,"A.-Error de compilación",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
15,1,1,"¿Cómo se llama el proceso de convertir un objeto de una subclase a su superclase?",NULL,B.-Upcasting,C.-Polimorfismo,D.-Instanciación,B,"Upcasting es el proceso de convertir un objeto de una subclase a su superclase en Java.",NULL,NULL,NULL,NULL,A.-Downcasting,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
16,1,1,"¿Cuál es el valor predeterminado de un atributo de instancia de tipo int en Java?",NULL,B.-0,C.-1,"D.-No tiene valor por defecto",B,"Los atributos de tipo int en Java tienen un valor predeterminado de 0.",NULL,NULL,NULL,NULL,A.-null,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
17,1,1,"¿Cuál de los siguientes no es un operador lógico en Java?",NULL,B.-||,C.-!,D.-%%,D,"El operador "%%" no existe en Java. Los operadores lógicos válidos son &&, || y !.",NULL,NULL,NULL,NULL,A.-&&,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
18,1,1,"¿Qué tipo de dato devuelve un método con la firma "public void metodo()"?",NULL,B.-void,C.-null,"D.-No devuelve nada",B,"El tipo "void" indica que el método no devuelve ningún valor.",NULL,NULL,NULL,NULL,A.-int,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
19,1,1,"¿Qué palabra clave se usa para definir una interfaz en Java?",NULL,B.-class,C.-interface,D.-implements,C,"La palabra clave "interface" se usa para definir interfaces en Java.",NULL,NULL,NULL,NULL,A.-abstract,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
20,1,1,"¿Cuál es la salida de System.out.println(2 + "3"); en Java?",NULL,B.-23,"C.-Error de compilación","D.-Ninguna de las anteriores",B,"En Java, si se concatena un número con un string, el número se convierte en string.",NULL,NULL,NULL,NULL,A.-5,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
21,1,1,"¿Qué método se ejecuta automáticamente cuando se instancia una clase en Java?",NULL,B.-start(),C.-constructor,D.-initialize(),C,"El constructor es el método que se ejecuta automáticamente al instanciar una clase en Java.",NULL,NULL,NULL,NULL,A.-run(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
22,2,1,"¿Cuál es la función de la instrucción "def" en Python?",NULL,"B.-Definir una función","C.-Importar un módulo","D.-Declarar una variable",B,"La palabra clave "def" en Python se usa para definir funciones.",NULL,NULL,NULL,NULL,"A.-Definir una clase",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
23,2,1,"¿Qué operador se usa para calcular el módulo de una división en Python?",NULL,B.-//,C.-/,D.-*,A,"El operador "%" se usa para obtener el residuo de una división en Python.",NULL,NULL,NULL,NULL,A.-%,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
24,2,1,"¿Cómo se declara una lista en Python?",NULL,"B.-list = [1,2,3]","C.-list = (1,2,3)","D.-list = <1,2,3>",B,"Las listas en Python se declaran con corchetes [].",NULL,NULL,NULL,NULL,"A.-list = {1,2,3}",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
25,2,1,"¿Cuál de los siguientes no es un tipo de dato en Python?",NULL,B.-float,C.-char,D.-bool,C,"Python no tiene un tipo de dato "char"; los caracteres son cadenas de un solo carácter.",NULL,NULL,NULL,NULL,A.-int,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
26,2,1,"¿Cuál es la forma correcta de escribir un comentario en Python?",NULL,"B.-# Este es un comentario","C.-<!-- Este es un comentario -->","D.-/* Este es un comentario */",B,"En Python, los comentarios de una sola línea se escriben con "#".",NULL,NULL,NULL,NULL,"A.-// Este es un comentario",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
27,2,1,"¿Qué función se usa para obtener la longitud de una lista en Python?",NULL,B.-size(),C.-count(),D.-len(),D,"La función "len()" se usa para obtener la longitud de una lista en Python.",NULL,NULL,NULL,NULL,A.-length(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
28,2,1,"¿Cuál es la forma correcta de abrir un archivo en Python?",NULL,"B.-file = read("archivo.txt")","C.-file.open("archivo.txt")","D.-file = openFile("archivo.txt")",A,"La función "open()" se usa para abrir archivos en Python.",NULL,NULL,NULL,NULL,"A.-file = open("archivo.txt", "r")",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
29,2,1,"¿Cuál es el resultado de print(2 ** 3) en Python?",NULL,B.-8,C.-9,D.-Error,B,"El operador "**" en Python se usa para exponentes, por lo que 2 ** 3 es 8.",NULL,NULL,NULL,NULL,A.-6,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
30,2,1,"¿Cuál es el valor de la expresión bool([]) en Python?",NULL,B.-False,C.-Error,D.-None,B,"Las listas vacías en Python se evalúan como False en un contexto booleano.",NULL,NULL,NULL,NULL,A.-True,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
31,2,1,"¿Cómo se define una variable global dentro de una función en Python?",NULL,"B.-def global variable","C.-set global variable","D.-var global",A,"Para definir una variable global dentro de una función en Python, se usa la palabra clave "global".",NULL,NULL,NULL,NULL,"A.-global variable",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
32,2,1,"¿Qué método se usa para convertir un string en minúsculas en Python?",NULL,B.-lower(),C.-small(),D.-downcase(),B,"El método "lower()" convierte un string a minúsculas en Python.",NULL,NULL,NULL,NULL,A.-toLowerCase(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
33,2,1,"¿Qué tipo de estructura de control es "elif" en Python?",NULL,B.-Bucle,C.-Función,D.-Excepción,A,"El "elif" en Python se usa en estructuras condicionales.",NULL,NULL,NULL,NULL,A.-Condicional,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
34,2,1,"¿Cuál de los siguientes métodos se usa para agregar un elemento a una lista en Python?",NULL,B.-insert(),C.-append(),D.-push(),C,"El método "append()" agrega un elemento al final de una lista en Python.",NULL,NULL,NULL,NULL,A.-add(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
35,2,1,"¿Qué devuelve la función type(5) en Python?",NULL,"B.-<class 'int'>","C.-"integer"",D.-Error,B,"La función "type()" devuelve el tipo de dato de un valor en Python.",NULL,NULL,NULL,NULL,"A.-"int"",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
36,2,1,"¿Cuál es la forma correcta de definir un diccionario en Python?",NULL,"B.-dict = {key1: value1, key2: value2}","C.-dict = (key1: value1, key2: value2)","D.-dict = <key1: value1, key2: value2>",B,"Los diccionarios en Python se definen con llaves {}.",NULL,NULL,NULL,NULL,"A.-dict = [key1: value1, key2: value2]",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
37,2,1,"¿Cuál es la función de la instrucción "import" en Python?",NULL,"B.-Definir variables","C.-Declarar funciones","D.-Ejecutar código externo",A,"La palabra clave "import" se usa para importar módulos en Python.",NULL,NULL,NULL,NULL,"A.-Importar módulos",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
39,2,1,"¿Cuál es la función de la palabra clave "pass" en Python?",NULL,"B.-Ignorar una línea de código","C.-Definir una función vacía","D.-Cerrar un archivo",C,"La palabra clave "pass" se usa como marcador de posición en funciones o clases vacías.",NULL,NULL,NULL,NULL,"A.-Terminar un bucle",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
40,2,1,"¿Cuál es la salida de print("Python"[::-1])?",NULL,"B.-"Python"",C.-Error,D.-None,A,"El operador de slicing "[::-1]" invierte una cadena en Python.",NULL,NULL,NULL,NULL,"A.-"nohtyP"",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
41,3,1,"¿Qué instrucción se usa para seleccionar todos los registros de una tabla en SQL?",NULL,"B.-SELECT * FROM tabla","C.-SHOW * FROM tabla","D.-FETCH * FROM tabla",B,"La instrucción correcta para seleccionar todos los registros es "SELECT * FROM tabla".",NULL,NULL,NULL,NULL,"A.-GET * FROM tabla",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
42,3,1,"¿Qué cláusula se usa para filtrar resultados en una consulta SQL?",NULL,B.-WHERE,C.-HAVING,"D.-ORDER BY",B,"La cláusula "WHERE" se usa para filtrar registros en una consulta SQL.",NULL,NULL,NULL,NULL,A.-FILTER,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
43,3,1,"¿Cuál de los siguientes comandos se usa para eliminar una tabla en SQL?",NULL,"B.-DELETE TABLE nombre_tabla","C.-DROP TABLE nombre_tabla","D.-CLEAR TABLE nombre_tabla",C,"El comando "DROP TABLE" elimina completamente una tabla y sus datos.",NULL,NULL,NULL,NULL,"A.-REMOVE TABLE nombre_tabla",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
44,3,1,"¿Cómo se renombra una tabla en SQL?",NULL,"B.-CHANGE TABLE tabla TO nueva_tabla","C.-ALTER TABLE tabla RENAME TO nueva_tabla","D.-RENAME TABLE tabla TO nueva_tabla",D,"El comando "RENAME TABLE nombre_actual TO nuevo_nombre" cambia el nombre de una tabla en SQL.",NULL,NULL,NULL,NULL,"A.-MODIFY TABLE tabla RENAME TO nueva_tabla",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
45,3,1,"¿Cuál de las siguientes opciones es una restricción de SQL?",NULL,B.-CHECK,"C.-NOT NULL","D.-Todas las anteriores",D,"Las restricciones en SQL incluyen PRIMARY KEY, CHECK, NOT NULL, y otras.",NULL,NULL,NULL,NULL,"A.-PRIMARY KEY",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
46,3,1,"¿Qué comando se usa para actualizar datos en una tabla en SQL?",NULL,B.-UPDATE,C.-MODIFY,D.-SET,B,"El comando "UPDATE" se usa para modificar registros existentes en una tabla.",NULL,NULL,NULL,NULL,A.-CHANGE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
47,3,1,"¿Cómo se obtiene el número total de registros en una tabla en SQL?",NULL,B.-SUM(*),C.-TOTAL(*),D.-LENGTH(*),A,"La función "COUNT(*)" devuelve el número total de registros en una tabla.",NULL,NULL,NULL,NULL,A.-COUNT(*),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
48,3,1,"¿Cuál de las siguientes cláusulas se usa para ordenar los resultados de una consulta SQL?",NULL,"B.-ORDER BY","C.-GROUP BY","D.-RANK BY",B,"La cláusula "ORDER BY" ordena los resultados de una consulta SQL.",NULL,NULL,NULL,NULL,"A.-SORT BY",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
49,3,1,"¿Cómo se seleccionan registros únicos en SQL?",NULL,"B.-SELECT UNIQUE columna FROM tabla","C.-SELECT DIFFERENT columna FROM tabla","D.-SELECT DISTINCTIVE columna FROM tabla",A,"La palabra clave "DISTINCT" permite seleccionar valores únicos en SQL.",NULL,NULL,NULL,NULL,"A.-SELECT DISTINCT columna FROM tabla",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
50,3,1,"¿Cuál es el propósito de la cláusula GROUP BY en SQL?",NULL,"B.-Agrupar registros con valores en común","C.-Eliminar registros duplicados","D.-Filtrar datos en una consulta",B,"La cláusula "GROUP BY" se usa para agrupar filas que tienen valores idénticos en columnas específicas.",NULL,NULL,NULL,NULL,"A.-Ordenar los registros",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
51,3,1,"¿Cuál es la función de la cláusula HAVING en SQL?",NULL,"B.-Ordenar los datos en una consulta","C.-Eliminar registros duplicados","D.-Limitar el número de registros en una consulta",A,"La cláusula "HAVING" se usa para filtrar datos después de aplicar "GROUP BY".",NULL,NULL,NULL,NULL,"A.-Filtrar resultados después de agrupar con GROUP BY",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
52,3,1,"¿Cuál es la diferencia entre DELETE y TRUNCATE en SQL?",NULL,"B.-DELETE elimina la tabla completa, TRUNCATE solo los registros","C.-DELETE y TRUNCATE son sinónimos","D.-DELETE solo borra algunos registros, TRUNCATE borra la base de datos",A,"DELETE permite eliminar registros específicos con WHERE, mientras que TRUNCATE borra toda la tabla de manera rápida y sin registrar cada eliminación individualmente.",NULL,NULL,NULL,NULL,"A.-DELETE borra registros individualmente, TRUNCATE borra todos sin registro en logs",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
53,3,1,"¿Cómo se crea una nueva base de datos en SQL?",NULL,"B.-CREATE DATABASE nombre","C.-ADD DATABASE nombre","D.-MAKE DATABASE nombre",B,"El comando "CREATE DATABASE nombre" se usa para crear una nueva base de datos.",NULL,NULL,NULL,NULL,"A.-NEW DATABASE nombre",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
54,3,1,"¿Cuál es el comando para agregar una nueva columna a una tabla en SQL?",NULL,"B.-ALTER TABLE ... ADD COLUMN","C.-INSERT COLUMN","D.-MODIFY TABLE ... ADD COLUMN",B,"El comando "ALTER TABLE tabla ADD COLUMN nombre_columna tipo_dato" se usa para añadir columnas a una tabla existente.",NULL,NULL,NULL,NULL,"A.-ADD COLUMN",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
55,3,1,"¿Cómo se elimina un solo registro de una tabla en SQL?",NULL,"B.-REMOVE FROM tabla WHERE id = valor","C.-DROP FROM tabla WHERE id = valor","D.-ERASE FROM tabla WHERE id = valor",A,"El comando correcto es "DELETE FROM tabla WHERE id = valor".",NULL,NULL,NULL,NULL,"A.-DELETE FROM tabla WHERE id = valor",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
56,3,1,"¿Qué comando se usa para hacer una copia de seguridad de una base de datos en SQL?",NULL,"B.-EXPORT DATABASE nombre","C.-SAVE DATABASE nombre","D.-DUMP DATABASE nombre",A,"El comando "BACKUP DATABASE nombre" se usa para crear una copia de seguridad en SQL.",NULL,NULL,NULL,NULL,"A.-BACKUP DATABASE nombre",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
57,3,1,"¿Cuál es la estructura básica de una consulta SQL?",NULL,"B.-SELECT columna FROM tabla","C.-FETCH columna FROM tabla","D.-SHOW columna FROM tabla",B,"La estructura básica de una consulta SQL es "SELECT columna FROM tabla".",NULL,NULL,NULL,NULL,"A.-GET columna FROM tabla",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
58,3,1,"¿Qué hace la cláusula LIMIT en una consulta SQL?",NULL,"B.-Ordena los registros de la consulta","C.-Agrupa los datos en la consulta","D.-Elimina registros duplicados",A,"La cláusula "LIMIT" restringe la cantidad de registros devueltos por una consulta SQL.",NULL,NULL,NULL,NULL,"A.-Limita el número de registros devueltos",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
59,3,1,"¿Cómo se combinan registros de dos tablas en SQL?",NULL,"B.-COMBINE TABLES","C.-MERGE TABLES","D.-USING UNION",D,"El operador "UNION" combina los resultados de dos consultas SQL.",NULL,NULL,NULL,NULL,"A.-USING JOIN",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
60,3,1,"¿Qué operador se usa para buscar un patrón de texto en SQL?",NULL,B.-FIND,C.-MATCH,D.-SEARCH,A,"El operador "LIKE" permite buscar patrones en columnas de texto en SQL.",NULL,NULL,NULL,NULL,A.-LIKE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
61,4,1,"¿Cuál es la principal responsabilidad del Product Owner en un equipo Scrum?",NULL,"B.- Asegurar que se sigan las reglas de Scrum","C.- Maximizar el valor del producto y gestionar el Product Backlog","D.- Redactar reportes de avance para la gerencia",C,"El Product Owner es responsable de maximizar el valor del producto y gestionar el Product Backlog.",NULL,NULL,NULL,NULL,"A.- Gestionar el equipo de desarrollo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
62,4,1,"¿Qué rol en Scrum es responsable de remover impedimentos para el equipo?",NULL,"B.- Scrum Master","C.- Project Manager","D.- Desarrollador líder",B,"El Scrum Master facilita el trabajo del equipo y remueve impedimentos que puedan afectar el avance.",NULL,NULL,NULL,NULL,"A.- Product Owner",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
63,4,1,"¿Quién decide cómo se implementa el trabajo del Sprint en Scrum?",NULL,"B.- El Product Owner","C.- El equipo de desarrollo","D.- El gerente del proyecto",C,"El equipo de desarrollo es autoorganizado y decide cómo hacer el trabajo.",NULL,NULL,NULL,NULL,"A.- El Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
64,4,1,"¿Cuál es una característica clave del Scrum Master?",NULL,"B.- Es un líder servicial que guía al equipo","C.- Es responsable del presupuesto del proyecto","D.- Es el único que puede modificar el Product Backlog",B,"El Scrum Master es un líder servicial, no un jefe. Ayuda al equipo a aplicar Scrum efectivamente.",NULL,NULL,NULL,NULL,"A.- Controla al equipo de desarrollo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
65,4,1,"¿Quién es responsable de priorizar los elementos del Product Backlog?",NULL,"B.- Development Team","C.- Product Owner","D.- Stakeholders",C,"El Product Owner es el único responsable de la priorización del Product Backlog.",NULL,NULL,NULL,NULL,"A.- Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
66,4,1,"¿Qué actividad realiza el Product Owner durante el Sprint Planning?",NULL,"B.- Estima el esfuerzo de cada tarea","C.- Define el objetivo del Sprint y prioriza los ítems del backlog","D.- Asigna tareas a los desarrolladores",C,"El Product Owner colabora en la definición del objetivo del Sprint y ayuda a priorizar el backlog.",NULL,NULL,NULL,NULL,"A.- Supervisa al equipo de desarrollo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
67,4,1,"¿Cuál es el papel del Scrum Master en la Daily Scrum?",NULL,"B.- Asignar tareas pendientes","C.- Facilitar la reunión si es necesario y asegurarse de que se realice","D.- Evaluar el desempeño individual del equipo",C,"La Daily Scrum es para el equipo, pero el Scrum Master vela por su realización y facilita si es necesario.",NULL,NULL,NULL,NULL,"A.- Liderar la reunión y tomar decisiones técnicas",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
68,4,1,"¿Quién tiene la última palabra sobre el contenido del Product Backlog?",NULL,"B.- Stakeholders","C.- Product Owner","D.- Equipo de desarrollo",C,"El Product Owner es el único responsable del contenido y orden del Product Backlog.",NULL,NULL,NULL,NULL,"A.- Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
69,4,1,"¿Quién puede modificar el Product Backlog?",NULL,"B.- El Product Owner","C.- El Scrum Master","D.- El cliente directamente",B,"El Product Owner es responsable de gestionar y modificar el Product Backlog.",NULL,NULL,NULL,NULL,"A.- Cualquier miembro del equipo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
70,4,1,"¿Quién evalúa el trabajo completado durante la Sprint Review?",NULL,"B.- El Product Owner con el equipo de desarrollo y stakeholders","C.- El equipo de desarrollo de forma privada","D.- Un auditor externo",B,"Durante la Sprint Review se presenta el incremento terminado y se discute con stakeholders y el Product Owner.",NULL,NULL,NULL,NULL,"A.- Solo el Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
71,5,1,"¿Cuál es la estructura típica de una historia de usuario?",NULL,"B.- Quiero, necesito, deseo","C.- Como <rol>, quiero <acción>, para <beneficio>","D.- Quién, cuándo y dónde",C,"La forma más común es: "Como [rol], quiero [funcionalidad], para [beneficio]".",NULL,NULL,NULL,NULL,"A.- Qué, cómo y por qué",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
72,5,1,"¿Qué NO debería incluir una historia de usuario?",NULL,"B.- Requisitos técnicos detallados","C.- Criterios de aceptación","D.- Objetivo de negocio",B,"Las historias de usuario deben centrarse en el valor para el usuario, no en detalles técnicos.",NULL,NULL,NULL,NULL,"A.- Roles y beneficios",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
73,5,1,"¿Quién es el principal responsable de redactar las historias de usuario?",NULL,"B.- El equipo de desarrollo","C.- El Product Owner","D.- Los testers",C,"El Product Owner es el responsable de gestionar y redactar las historias de usuario en el backlog.",NULL,NULL,NULL,NULL,"A.- El Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
74,5,1,"¿Qué representa la "I" en el acrónimo INVEST relacionado con historias de usuario?",NULL,"B.- Independiente","C.- Integrada","D.- Inteligente",B,"INVEST es un acrónimo para evaluar historias: Independiente, Negociable, Valiosa, Estimable, Small y Testable.",NULL,NULL,NULL,NULL,"A.- Iterativa",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
75,5,1,"¿Cuál es el propósito de los criterios de aceptación en una historia de usuario?",NULL,"B.- Calcular el tiempo de desarrollo exacto","C.- Establecer las condiciones bajo las cuales se considera que está completa","D.- Asignar prioridades",C,"Los criterios de aceptación permiten definir claramente cuándo una historia está terminada y es funcional.",NULL,NULL,NULL,NULL,"A.- Determinar quién la va a programar",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
76,5,1,"¿Cuál es el principal beneficio de usar historias de usuario en Scrum?",NULL,"B.- Facilitan la estimación técnica detallada","C.- Ayudan a enfocarse en el valor para el usuario final","D.- Reemplazan toda la documentación del proyecto",C,"Las historias de usuario permiten mantener el enfoque en el valor que el producto entrega al usuario.",NULL,NULL,NULL,NULL,"A.- Permiten medir el desempeño del equipo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
77,5,1,"¿Qué característica NO corresponde a una buena historia de usuario?",NULL,"B.- Completamente detallada desde el inicio","C.- Independiente de otras historias","D.- Valiosa para el cliente",B,"Las historias de usuario no deben estar completamente detalladas desde el inicio, deben permitir colaboración y discusión.",NULL,NULL,NULL,NULL,"A.- Pequeña y manejable",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
78,5,1,"¿Cuándo se considera que una historia de usuario está lista para incluirse en un Sprint?",NULL,"B.- Cuando tiene una estimación exacta de horas","C.- Cuando cumple con la Definition of Ready","D.- Cuando ha sido votada por los stakeholders",C,"La Definition of Ready (DoR) define los criterios que debe cumplir una historia para estar lista para un Sprint.",NULL,NULL,NULL,NULL,"A.- Cuando ha sido aprobada por el Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
79,5,1,"¿Quiénes participan en el refinamiento del Product Backlog donde se discuten historias de usuario?",NULL,"B.- Solo los stakeholders","C.- El Product Owner y el equipo de desarrollo","D.- Cualquier persona interesada del proyecto",C,"El Product Owner lidera el refinamiento, pero el equipo de desarrollo colabora activamente para aclarar y estimar historias.",NULL,NULL,NULL,NULL,"A.- Solo el Product Owner y el Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
80,5,1,"¿Cuál es una diferencia clave entre una historia de usuario y una tarea técnica?",NULL,"B.- Las historias de usuario se enfocan en el usuario y su valor","C.- Las historias técnicas no necesitan criterios de aceptación","D.- Las historias de usuario no se estiman",B,"Las historias de usuario están orientadas a la experiencia del usuario final, mientras que las tareas técnicas se centran en el cómo.",NULL,NULL,NULL,NULL,"A.- Las tareas técnicas son siempre más importantes",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
81,7,1,"¿Qué evento marca el inicio oficial de un Sprint en Scrum?",NULL,"B.- La retrospectiva del Sprint anterior","C.- La planificación del Sprint (Sprint Planning)","D.- La revisión del Sprint (Sprint Review)",C,"El Sprint comienza con la reunión de planificación del Sprint, donde se define qué se hará y cómo se hará.",NULL,NULL,NULL,NULL,"A.- La reunión diaria (Daily Scrum)",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
82,7,1,"¿Qué evento marca la conclusión de un Sprint?",NULL,"B.- Sprint Planning","C.- Sprint Retrospective","D.- Sprint Review",C,"El Sprint finaliza con la Sprint Retrospective, donde el equipo reflexiona sobre cómo mejorar en el siguiente Sprint.",NULL,NULL,NULL,NULL,"A.- Daily Scrum",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
83,7,1,"¿Cuál es el propósito principal del Daily Scrum?",NULL,"B.- Revisar los avances y planear el trabajo del día","C.- Cambiar el Sprint Backlog","D.- Revisar el presupuesto del proyecto",B,"El Daily Scrum es una reunión diaria de 15 minutos donde los desarrolladores sincronizan su trabajo y planifican el día.",NULL,NULL,NULL,NULL,"A.- Discutir problemas personales del equipo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
84,7,1,"¿Qué sucede durante la Sprint Review?",NULL,"B.- El equipo presenta lo que se completó durante el Sprint","C.- Se identifican conflictos personales","D.- Se asignan tareas al siguiente Sprint",B,"Durante la Sprint Review, el equipo muestra el incremento desarrollado y recoge retroalimentación del Product Owner y stakeholders.",NULL,NULL,NULL,NULL,"A.- Se cancelan historias no completadas",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
85,7,1,"¿Qué es un Sprint en el marco de trabajo Scrum?",NULL,"B.- Un ciclo de trabajo fijo en el que se crea un incremento del producto","C.- Una entrega final al cliente","D.- Un evento para revisar el rendimiento del equipo",B,"El Sprint es el corazón de Scrum: un período de tiempo fijo (generalmente de 2 a 4 semanas) donde se crea un incremento usable y potencialmente entregable.",NULL,NULL,NULL,NULL,"A.- Una reunión de planificación",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
86,7,1,"¿Quién es responsable de facilitar la Retrospectiva del Sprint?",NULL,"B.- El Scrum Master","C.- El equipo completo sin líder","D.- El Project Manager",B,"El Scrum Master facilita la Retrospectiva del Sprint para ayudar al equipo a inspeccionar y adaptar su forma de trabajar.",NULL,NULL,NULL,NULL,"A.- El Product Owner",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
87,7,1,"¿Cuál de las siguientes actividades NO es propia de una Sprint Retrospective?",NULL,"B.- Evaluar al Product Owner","C.- Plantear mejoras para el próximo Sprint","D.- Revisar dificultades enfrentadas",B,"En la Retrospectiva se enfoca en el proceso y la colaboración del equipo, no en evaluar personas individualmente.",NULL,NULL,NULL,NULL,"A.- Identificar qué funcionó bien",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
88,7,1,"¿Qué se inspecciona principalmente durante la Sprint Review?",NULL,"B.- El incremento del producto desarrollado","C.- El presupuesto del proyecto","D.- Los conflictos personales del equipo",B,"En la Sprint Review se inspecciona el incremento creado durante el Sprint y se obtiene retroalimentación para ajustar el Product Backlog.",NULL,NULL,NULL,NULL,"A.- El desempeño individual del equipo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
90,6,1,"¿Cuál es la duración máxima recomendada del Daily Scrum?",NULL,"B.- 30 minutos","C.- 45 minutos","D.- 15 minutos",D,"El Daily Scrum debe durar como máximo 15 minutos para ser ágil y eficiente.",NULL,NULL,NULL,NULL,"A.- 60 minutos",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
91,6,1,"¿Quiénes deben participar activamente en el Daily Scrum?",NULL,"B.- Solo el Scrum Master","C.- Todo el equipo de desarrollo","D.- Solo los líderes del equipo",C,"El Daily Scrum está diseñado para el equipo de desarrollo, quienes lo conducen y lo aprovechan para coordinar el trabajo.",NULL,NULL,NULL,NULL,"A.- Solo el Product Owner",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
92,6,1,"¿Cuál de los siguientes temas es apropiado para discutir en el Daily Scrum?",NULL,"B.- Problemas personales entre miembros del equipo","C.- El trabajo realizado ayer, lo que se hará hoy y los impedimentos","D.- Resultados de encuestas de satisfacción del cliente",C,"El equipo comparte lo que hizo ayer, lo que hará hoy y cualquier impedimento que afecte el trabajo.",NULL,NULL,NULL,NULL,"A.- Cambios en el presupuesto",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
93,6,1,"¿Quién debe facilitar el Daily Scrum?",NULL,"B.- El Scrum Master","C.- Cualquier miembro del equipo de desarrollo","D.- Un líder designado por la empresa",C,"En Scrum, el Daily Scrum es autoorganizado por el equipo de desarrollo. No es facilitado por el Scrum Master, aunque puede apoyar si se solicita.",NULL,NULL,NULL,NULL,"A.- El Product Owner",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
94,8,1,"¿Cuántas ceremonias principales existen en Scrum?",NULL,"B.- 4","C.- 5","D.- 6",B,"Scrum tiene 4 ceremonias principales: Sprint Planning, Daily Scrum, Sprint Review y Sprint Retrospective.",NULL,NULL,NULL,NULL,"A.- 3",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
95,8,1,"¿Cuál es el propósito de la ceremonia Sprint Planning?",NULL,"B.- Reunirse con el cliente","C.- Planificar el trabajo que se realizará durante el Sprint","D.- Presentar informes financieros",C,"El Sprint Planning se utiliza para definir qué se hará durante el Sprint y cómo se logrará.",NULL,NULL,NULL,NULL,"A.- Revisar los errores del Sprint anterior",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
96,8,1,"¿Cuándo se realiza la Sprint Review?",NULL,"B.- Cada mañana","C.- Justo después de la Sprint Retrospective","D.- Al final del Sprint",D,"La Sprint Review se realiza al final del Sprint para mostrar el incremento al Product Owner y partes interesadas.",NULL,NULL,NULL,NULL,"A.- Al inicio del Sprint",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
97,8,1,"¿Qué ceremonia de Scrum se enfoca en mejorar los procesos del equipo?",NULL,"B.- Daily Scrum","C.- Sprint Retrospective","D.- Sprint Planning",C,"La Sprint Retrospective permite al equipo reflexionar sobre cómo mejorar su trabajo y procesos.",NULL,NULL,NULL,NULL,"A.- Sprint Review",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
98,8,1,"¿Qué sucede durante la ceremonia Daily Scrum?",NULL,"B.- El Product Owner define prioridades","C.- El equipo sincroniza su trabajo y detecta impedimentos","D.- Se presentan estadísticas del proyecto al cliente",C,"Durante el Daily Scrum, el equipo se reúne brevemente para coordinar esfuerzos y detectar obstáculos.",NULL,NULL,NULL,NULL,"A.- Se revisan los entregables finales del Sprint",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
99,9,1,"¿Qué es una épica en Scrum?",NULL,"B.- Un conjunto de historias de usuario relacionadas que representan una funcionalidad grande","C.- Una tarea repetitiva que se realiza en cada Sprint","D.- Un reporte de desempeño del equipo",B,"Una épica es una gran historia de usuario que debe dividirse en historias más pequeñas para ser manejable.",NULL,NULL,NULL,NULL,"A.- Una reunión de planificación extendida",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
100,9,1,"¿Cuál es una característica común de una épica en Scrum?",NULL,"B.- Es una actividad diaria","C.- Es demasiado grande para ser completada en un solo Sprint","D.- Requiere aprobación del cliente en cada iteración",C,"Las épicas generalmente son demasiado grandes para ser completadas en un solo Sprint y deben dividirse.",NULL,NULL,NULL,NULL,"A.- Se completa en un solo Sprint",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
101,9,1,"¿Dónde se documentan las épicas en Scrum?",NULL,"B.- En el Sprint Backlog","C.- En la Retrospectiva","D.- En el Daily Scrum",A,"Las épicas, como todas las historias de usuario, se documentan en el Product Backlog.",NULL,NULL,NULL,NULL,"A.- En el Product Backlog",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
102,9,1,"¿Quién es responsable de gestionar las épicas dentro del equipo Scrum?",NULL,"B.- El Scrum Master","C.- El Product Owner","D.- El cliente",C,"El Product Owner es responsable de gestionar el Product Backlog, incluyendo las épicas.",NULL,NULL,NULL,NULL,"A.- El equipo de desarrollo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
103,9,1,"¿Qué debe hacerse con una épica antes de incluirla en un Sprint?",NULL,"B.- Convertirla en tareas técnicas","C.- Dividirla en historias de usuario más pequeñas","D.- Moverla directamente al Sprint Backlog",C,"Las épicas deben dividirse en historias de usuario más pequeñas y manejables antes de agregarlas a un Sprint.",NULL,NULL,NULL,NULL,"A.- Aprobarla con el cliente final",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
104,10,1,"¿Qué gráfica se usa comúnmente para visualizar el progreso diario en un Sprint?",NULL,"B.- Diagrama de Gantt","C.- Gráfica de Burn Down","D.- Gráfica de barras",C,"La gráfica de Burn Down muestra cuánto trabajo queda por hacer y ayuda a visualizar el progreso del Sprint.",NULL,NULL,NULL,NULL,"A.- Gráfica de flujo acumulativo",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
105,10,1,"¿Qué representa el eje Y en una gráfica de Burn Down?",NULL,"B.- La cantidad de trabajo restante","C.- El número de errores encontrados","D.- La velocidad del equipo",B,"En una gráfica de Burn Down, el eje Y representa la cantidad de trabajo restante (por ejemplo, en horas o puntos de historia).",NULL,NULL,NULL,NULL,"A.- El tiempo transcurrido",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
106,10,1,"¿Qué permite visualizar una gráfica de flujo acumulativo?",NULL,"B.- El trabajo planificado y el real completado","C.- El flujo de trabajo y los cuellos de botella","D.- Las tareas asignadas a cada miembro del equipo",C,"La gráfica de flujo acumulativo muestra cómo fluye el trabajo a través del sistema, ayudando a identificar cuellos de botella.",NULL,NULL,NULL,NULL,"A.- La velocidad del equipo en cada Sprint",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
107,10,1,"¿Qué puede indicar una línea plana en la gráfica de Burn Down durante varios días?",NULL,"B.- Que no se ha completado trabajo durante ese periodo","C.- Que el Product Owner ha agregado nuevas historias","D.- Que el Sprint ha finalizado",B,"Una línea plana en la gráfica de Burn Down indica que no se ha completado trabajo en ese periodo.",NULL,NULL,NULL,NULL,"A.- Que el equipo ha completado mucho trabajo rápidamente",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
108,10,1,"¿Cuál es el propósito principal de las gráficas en Scrum?",NULL,"B.- Visualizar el progreso y facilitar la toma de decisiones","C.- Informar a los clientes sobre problemas financieros","D.- Crear reportes para la alta dirección",B,"Las gráficas en Scrum ayudan a visualizar el trabajo del equipo y facilitan la toma de decisiones informadas.",NULL,NULL,NULL,NULL,"A.- Controlar el trabajo del equipo de forma estricta",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
109,11,1,"¿Cuál de los siguientes es un artefacto oficial de Scrum?",NULL,"B.- Product Backlog","C.- Documento de requerimientos funcionales","D.- Matriz RACI",B,"El Product Backlog es uno de los artefactos oficiales de Scrum, junto con el Sprint Backlog y el Incremento.",NULL,NULL,NULL,NULL,"A.- Diagrama de Gantt",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
110,11,1,"¿Qué contiene el Sprint Backlog?",NULL,"B.- Los entregables completos del proyecto","C.- Las tareas seleccionadas del Product Backlog para el Sprint actual","D.- Una lista de errores encontrados en producción",C,"El Sprint Backlog contiene los elementos del Product Backlog seleccionados para el Sprint actual, junto con un plan para entregarlos.",NULL,NULL,NULL,NULL,"A.- Todas las tareas del proyecto",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
111,11,1,"¿Qué representa el Incremento en Scrum?",NULL,"B.- Una historia de usuario incompleta","C.- La suma de todos los elementos completados del Product Backlog","D.- El backlog del próximo Sprint",C,"El Incremento es la suma de todos los elementos del Product Backlog completados durante el Sprint y los Sprints anteriores.",NULL,NULL,NULL,NULL,"A.- Un error corregido",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
112,11,1,"¿Quién es responsable de mantener el Product Backlog?",NULL,"B.- Stakeholders","C.- Equipo de desarrollo","D.- Product Owner",D,"El Product Owner es responsable de mantener, priorizar y actualizar el Product Backlog.",NULL,NULL,NULL,NULL,"A.- Scrum Master",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
113,11,1,"¿Qué se necesita para que un Incremento sea considerado "Hecho" en Scrum?",NULL,"B.- Que cumpla con la definición de "Terminado" del equipo","C.- Que esté documentado en una presentación","D.- Que el Scrum Master lo valide",B,"Para que un Incremento sea considerado "Hecho", debe cumplir con la definición de "Terminado" acordada por el equipo Scrum.",NULL,NULL,NULL,NULL,"A.- Que el cliente lo apruebe",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
114,12,1,"¿Qué es una vista materializada en SQL?",NULL,"B.- Una vista que almacena físicamente los datos en disco","C.- Una consulta que se ejecuta cada vez que se accede a la vista","D.- Una función almacenada",B,"Una vista materializada guarda físicamente los resultados de una consulta, mejorando el rendimiento en lecturas.",NULL,NULL,NULL,NULL,"A.- Una tabla temporal que desaparece al cerrar sesión",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
115,12,1,"¿Cuál es una ventaja principal de usar vistas materializadas?",NULL,"B.- Reducen el tiempo de procesamiento de consultas complejas","C.- Permiten modificar directamente los datos","D.- No requieren espacio en disco",B,"Las vistas materializadas almacenan los resultados, por lo que las consultas complejas se ejecutan más rápido.",NULL,NULL,NULL,NULL,"A.- Siempre muestran datos en tiempo real",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
116,12,1,"¿Qué comando se usa para actualizar los datos de una vista materializada?",NULL,"B.- REFRESH MATERIALIZED VIEW","C.- UPDATE MATERIALIZED","D.- COMMIT",B,"El comando correcto para actualizar los datos de una vista materializada es REFRESH MATERIALIZED VIEW.",NULL,NULL,NULL,NULL,"A.- ALTER VIEW",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
117,12,1,"¿Con qué frecuencia se pueden actualizar las vistas materializadas?",NULL,"B.- Nunca","C.- Manual o automáticamente según configuración","D.- Solo cuando cambia el esquema de la base de datos",C,"Las vistas materializadas pueden actualizarse manualmente o con una programación automática definida.",NULL,NULL,NULL,NULL,"A.- Sólo al crearlas",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
118,12,1,"¿Cuál es una diferencia entre una vista normal y una vista materializada?",NULL,"B.- La vista materializada se actualiza en tiempo real","C.- La vista normal siempre es más rápida que la materializada","D.- La vista materializada almacena datos físicamente, la normal no",D,"La vista materializada guarda físicamente los datos, mientras que la vista normal solo define una consulta sin almacenar datos.",NULL,NULL,NULL,NULL,"A.- La vista normal almacena datos, la materializada no",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
119,13,1,"¿Qué es una consulta dinámica en SQL o PL/SQL?",NULL,"B.- Una consulta almacenada en una vista","C.- Una consulta construida y ejecutada en tiempo de ejecución","D.- Una consulta que sólo se usa en triggers",C,"Las consultas dinámicas se construyen como cadenas de texto y se ejecutan en tiempo de ejecución, permitiendo mayor flexibilidad.",NULL,NULL,NULL,NULL,"A.- Una consulta que se escribe en tiempo de compilación",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
120,13,1,"¿Qué función se utiliza en PL/SQL para ejecutar una consulta dinámica?",NULL,"B.- EXECUTE IMMEDIATE","C.- RUN SQL","D.- DBMS_EXECUTE",B,"EXECUTE IMMEDIATE permite ejecutar sentencias SQL almacenadas en variables tipo cadena dentro de un bloque PL/SQL.",NULL,NULL,NULL,NULL,"A.- EXECUTE QUERY",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
121,13,1,"¿Cuál es una ventaja del uso de consultas dinámicas?",NULL,"B.- Facilidad para construir consultas estáticas","C.- Flexibilidad para construir sentencias en tiempo de ejecución","D.- Mejora el rendimiento en todos los casos",C,"Las consultas dinámicas permiten adaptarse a distintos escenarios en tiempo de ejecución, como condiciones o tablas variables.",NULL,NULL,NULL,NULL,"A.- Menor uso de recursos del sistema",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
122,13,1,"¿Qué riesgo común está asociado con el uso de consultas dinámicas?",NULL,"B.- Mal uso de los índices","C.- Inyección SQL","D.- Errores de sintaxis en vistas",C,"Si no se validan correctamente los valores usados en consultas dinámicas, pueden ocurrir ataques de inyección SQL.",NULL,NULL,NULL,NULL,"A.- Pérdida de memoria RAM",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
123,13,1,"¿Qué tipo de variable se debe usar en PL/SQL para almacenar una consulta dinámica?",NULL,"B.- DATE","C.- VARCHAR2","D.- NUMBER",C,"Las consultas dinámicas se almacenan como cadenas, por lo que se deben usar variables tipo VARCHAR2.",NULL,NULL,NULL,NULL,"A.- BOOLEAN",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
124,14,1,"¿Qué sucede si no se maneja una excepción en un bloque PL/SQL?",NULL,"B.- El bloque se salta","C.- Se lanza un error y se detiene la ejecución","D.- La excepción se convierte en una advertencia",C,"Si una excepción no se maneja, el error se propaga y puede detener completamente la ejecución del programa.",NULL,NULL,NULL,NULL,"A.- El programa continúa normalmente",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
125,14,1,"¿Qué es una excepción en PL/SQL?",NULL,"B.- Una estructura de bucle","C.- Una condición de error o evento inesperado","D.- Un operador lógico",C,"Las excepciones son eventos que interrumpen el flujo normal del programa, como errores en tiempo de ejecución.",NULL,NULL,NULL,NULL,"A.- Un tipo de variable",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
126,14,1,"¿Cuál es la cláusula utilizada para capturar excepciones en PL/SQL?",NULL,"B.- IF ERROR THEN","C.- HANDLE ERROR","D.- ON ERROR DO",A,"La cláusula WHEN OTHERS THEN captura cualquier excepción no manejada previamente en un bloque EXCEPTION.",NULL,NULL,NULL,NULL,"A.- WHEN OTHERS THEN",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
128,14,1,"¿Qué hace la instrucción RAISE en PL/SQL?",NULL,"B.- Declara una variable","C.- Lanza una excepción manualmente","D.- Reinicia un bucle",C,"La instrucción RAISE permite generar una excepción de manera explícita para ser manejada en un bloque EXCEPTION.",NULL,NULL,NULL,NULL,"A.- Termina la ejecución del programa",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
129,14,1,"¿Qué tipo de excepción es NO_DATA_FOUND?",NULL,"B.- Predefinida por PL/SQL","C.- Excepción de sintaxis","D.- Error de compilación",B,"NO_DATA_FOUND es una excepción predefinida que ocurre cuando una consulta SELECT INTO no retorna datos.",NULL,NULL,NULL,NULL,"A.- Definida por el usuario",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
132,15,1,"¿Qué es un trigger en PL/SQL?",NULL,"B.- Una instrucción para manejar errores","C.- Un procedimiento que se ejecuta automáticamente al ocurrir un evento","D.- Un tipo de tabla temporal",C,"Un trigger es un bloque de código que se ejecuta automáticamente cuando ocurre un evento en una tabla, como un INSERT, UPDATE o DELETE.",NULL,NULL,NULL,NULL,"A.- Una consulta que devuelve múltiples resultados",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
133,15,1,"¿Cuál de los siguientes eventos puede activar un trigger?",NULL,"B.- MERGE","C.- UPDATE","D.- PRINT",C,"Los triggers se activan por eventos como INSERT, UPDATE y DELETE, no por consultas SELECT.",NULL,NULL,NULL,NULL,"A.- SELECT",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
134,15,1,"¿En qué momento se puede ejecutar un trigger?",NULL,"B.- Solo después del evento","C.- Antes o después del evento","D.- Solo durante la creación de la tabla",C,"Un trigger puede definirse para ejecutarse antes (BEFORE) o después (AFTER) de un evento como un INSERT, UPDATE o DELETE.",NULL,NULL,NULL,NULL,"A.- Solo antes del evento",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
135,15,1,"¿Qué palabra clave se usa para definir un trigger en PL/SQL?",NULL,"B.- CREATE TRIGGER","C.- CREATE FUNCTION","D.- DEFINE TRIGGER",B,"La definición de un trigger comienza con CREATE TRIGGER seguido del nombre y evento que lo activa.",NULL,NULL,NULL,NULL,"A.- CREATE PROCEDURE",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
136,15,1,"¿Cuál es el propósito principal de los triggers?",NULL,"B.- Ejecutar automáticamente acciones ante ciertos eventos","C.- Crear nuevas tablas dinámicamente","D.- Mejorar el rendimiento del servidor",B,"Los triggers permiten automatizar tareas cuando ocurren eventos como modificaciones a los datos en las tablas.",NULL,NULL,NULL,NULL,"A.- Optimizar las consultas",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
137,27,2,"El coste de realizar un ataque se denomina:",NULL,"B.- Cost to break.","C.- Cost to fix.","D.- Coste de reconstrucción.",B,NULL,NULL,NULL,1,1.1,"A.- Coste de ataque.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
138,27,2,"Para que la ciberseguridad sea rentable:",NULL,"B.- Coste construcción defensas < (cost to fix + perdida de beneficio + coste reconstrucción).","C.- Cost to fix < (perdida de beneficio).","D.- Cost to fix < (perdida de reconstrucción).",B,NULL,NULL,NULL,1,1.1,"A.- Es difícilmente rentable.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
139,27,2,"Del lado de la organización, los costes básicos son: coste de construcción de las medidas defensivas, coste de reparación de vulnerabilidades y…",NULL,"B.- Coste de ruptura.","C.- Coste de construcción.","D.- Ninguna de las anteriores.",A,NULL,NULL,NULL,1,1.1,"A.- Coste de reconstrucción de sistemas.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
140,27,2,"Al tipo de protesta con fines de activismo político, social o económico en forma de ataques cibernéticos. (Anonymous, Wikileaks…), se la denomina:",NULL,"B.- Doxxing.","C.- Hacktivismo.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,1.2,"A.- DDOS.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
141,27,2,"¿Cuál es el ataque relacionado con los actores internos más frecuente?",NULL,"B.- DDOS.","C.- Troyano","D.- Hacktivismo.",A,NULL,NULL,NULL,1,1.2,"A.- Phishing.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
142,27,2,"Las APTs son características de:",NULL,"B.- Actores estado.","C.- Hacktivistas.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,1.2,"A.- Actores internos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
143,27,2,"¿Cómo se puede asegurar la integridad de los sistemas?",NULL,"B.- Firma digital avanzada.","C.- Autenticación.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,1.3,"A.- Validación de entrada.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
144,27,2,"¿Para qué es necesario un correcto diseño de logging o registro?",NULL,"B.- Para garantizar la confidencialidad.","C.- Para garantizar la integridad.","D.- Para garantizar la disponibilidad.",A,NULL,NULL,NULL,1,1.3,"A.- Para garantizar la trazabilidad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
145,27,2,"Proporcionar la prueba de que una determinada transmisión o recepción ha sido realizada, sin que su receptor/transmisor pueda negar que se haya producido, se denomina:",NULL,"B.- Demostrar la identidad.","C.- Garantizar la integridad.","D.- No repudio.",D,NULL,NULL,NULL,1,1.3,"A.- Autenticar.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
146,27,2,"Las descripciones sobre cómo configurar determinados elementos de seguridad para que sean aplicados de manera uniforme en toda la organización se denominan:",NULL,"B.- Directrices.","C.- Líneas base.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,1.4,"A.- Política de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
147,27,2,"Las descripciones detalladas de los pasos para llevar a cabo una determinada tarea por los usuarios sin dudas se llaman:",NULL,"B.- Directrices.","C.- Líneas base.","D.- Ninguna de las anteriores.",A,NULL,NULL,NULL,1,1.4,"A.- Procedimientos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
148,27,2,"Los estándares, directrices y procedimientos son medios para implementar las:",NULL,"B.- Líneas base.","C.- Políticas.","D.- Las opciones A y C.",D,NULL,NULL,NULL,1,1.4,"A.- Medidas de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
149,27,2,"La política general de seguridad de una organización:",NULL,"B.- Establece qué herramientas y qué procedimientos son necesarios.","C.- Sirve para comunicar un consenso del uso de datos y aplicaciones dentro de la organización.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,2.1,"A.- Define el comportamiento apropiado para cada caso.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
150,27,2,"Un sistema de detección de intrusiones se usa en la fase de:",NULL,"B.- Análisis de vulnerabilidades.","C.- Implementación.","D.- Monitorización y análisis de vulnerabilidades.",A,NULL,NULL,NULL,1,2.1,"A.- Monitorización.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
151,27,2,"Un cortafuegos de instala en la fase de:",NULL,"B.- Análisis de vulnerabilidades.","C.- Implementación.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,2.1,"A.- Monitorización.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
152,27,2,"El tipo de norma que estandariza el uso de aspectos específicos del sistema (indican un uso correcto y responsabilidad del usuario y son obligatorias) se denomina:",NULL,"B.- Estándar.","C.- Guía de seguridad.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,2.2,"A.- Procedimientos de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
153,27,2,"El tipo de norma destinada a ayudar a los usuarios a aplicar las medidas de seguridad correctamente al proporcionar un razonamiento donde no se dispone de los procedimientos correctos, se denomina:",NULL,"B.- Estándar.","C.- Guía de seguridad.","D.- Ninguna de las anteriores",C,NULL,NULL,NULL,1,2.2,"A.- Procedimientos de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
154,27,2,"El tipo de norma que se ocupa de tareas específicas, mostrando cada paso que se debe realizar y que es muy útil en tareas que son repetitivas, como en un procedimiento de backup y recuperación, se denomina:",NULL,"B.- Estándar.","C.- Guía de seguridad.","D.- Ninguna de las anteriores.",A,NULL,NULL,NULL,1,2.2,"A.- Procedimientos de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
155,27,2,"Un sistema de gestión para la seguridad de la información:",NULL,"B.- Opera y mantiene los procesos establecidos para la seguridad de la información.","C.- Mide los resultados (monitorización) e indicadores de los distintos procesos de la seguridad de la información.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,2.3,"A.- Establece o planifica la seguridad de la información.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
156,27,2,"¿Cuál es la actividad más importante en un SGSI?",NULL,"B.- Elaborar procedimientos.","C.- Análisis y gestión de riesgos.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,2.3,"A.- Planificación.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
157,27,2,"La declaración de aplicabilidad de salvaguardas es propia de la fase (ISO27001):",NULL,"B.- PLAN: análisis de riesgos.","C.- PLAN: tratamiento de los riesgos.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,2.3,"A.- ACT: Mejora.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
158,27,2,"Una profesión puede caracterizarse por el desarrollo de algunos de los siguientes criterios:",NULL,"B.- El reconocimiento por parte de los clientes de la autoridad de la profesión.","C.- La aprobación de la comunidad de la autoridad de la profesión.","D.- Todas las anteriores son ciertas.",D,NULL,NULL,NULL,1,2.4,"A.- La creación de un cuerpo organizado de conocimientos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
159,27,2,"El hacker ético tiene como elemento interesante el situar:",NULL,"B.- La seguridad desde el contexto del atacante.","C.- La seguridad tanto desde el contexto del atacante como desde el contexto de defensa.","D.- Todas las anteriores son correctas",B,NULL,NULL,NULL,1,2.4,"A.- La seguridad desde el contexto defensivo.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
160,27,2,"Un ejemplo de recopilación de requisitos en el área (que puede considerarse como definitorio) de qué debe saber un profesional de la seguridad de la información sería:",NULL,"B.- No existen recopilaciones de requisitos adecuadas actualmente.","C.- El cuerpo de conocimiento (body of knowledge, BOK) del Consorcio Internacional de Certificación de Seguridad de Sistemas de Información o (ISC)2.","D.- Todas las anteriores son correctas",C,NULL,NULL,NULL,1,2.4,"A.- El decálogo OWASP.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
161,27,2,"La certificación Certified Information Systems Security Professional (CISSP) es certificada por:",NULL,"B.- ISACA.","C.- Certification and Accreditation Professional.","D.- International Information Systems Security Certification Consortium.",D,NULL,NULL,NULL,1,2.5,"A.- SANS.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
162,27,2,"La certificación Certified Information Systems Security Professional (CISSP), incluye:",NULL,"B.- Information Systems Security Architecture Professional (CISSP-ISSEP).","C.- Information Systems Security Architecture Professional (CISSP-ISMP).","D.- Todas las anteriores son correctas",D,NULL,NULL,NULL,1,2.5,"A.- Information Systems Security Architecture Professional (CISSP-ISSAP).",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
163,27,2,"Un CISSP está certificado como profesional para:",NULL,"B.- Desarrollar software seguro.","C.- Realizar auditorías de seguridad exclusivamente.","D.- Todas las anteriores son correctas.",A,NULL,NULL,NULL,1,2.5,"A.- Definir la arquitectura de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
164,27,2,"¿Cuál es una desventaja de OCTAVE?",NULL,"B.- La flexibilidad.","C.- Implica un elevado nivel de conocimientos tecnológicos y técnicos.","D.- A y B son correctas.",C,NULL,NULL,NULL,1,3.1,"A.- No establece explícitamente la identificación de vulnerabilidades como uno de los pasos de la metodología.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
165,27,2,"¿Cuál es la principal desventaja de MAGERIT?",NULL,"B.- Facilidad a la hora de traducir una estimación cualitativa a una cuantía económica.","C.- Implementación.","D.- Las opciones A y B son correctas.",A,NULL,NULL,NULL,1,3.1,"A.- No establece explícitamente la identificación de vulnerabilidades como uno de los pasos de la metodología.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
166,27,2,"MAGERIT está basada en las normas:",NULL,"B.- ISO 27002.","C.- ISO 27005.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,3.1,"A.- ISO 27001.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
167,27,2,"¿En qué fase se realiza la toma de decisiones?",NULL,"B.- Gestión de riesgos.","C.- Análisis de riesgos.","D.- Todas las anteriores son correctas.",B,NULL,NULL,NULL,1,3.2,"A.- Planificación.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
168,27,2,"En el comité de dirección existe la figura del:",NULL,"B.- Enlace de seguimiento.","C.- Interlocutor.","D.- Promotor.",D,NULL,NULL,NULL,1,3.2,"A.- Director del proyecto.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
169,27,2,"El director del proyecto y su equipo planifican toda la realización del proyecto a través de:",NULL,"B.- Participantes que entrevistar.","C.- Calendario.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,3.2,"A.- Plan de entrevistas que realizar.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
170,27,2,"El impacto es igual a:",NULL,"B.- Degradación del valor del activo.","C.- Riesgo acumulado por frecuencia.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,3.3,"A.- Valor por riesgo acumulado.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
171,27,2,"El actor o agente que es la fuente de peligro por diferentes motivaciones como factores económicos, de prestigio u otros, se denomina:",NULL,"B.- Activo.","C.- Amenaza.","D.- Ataque.",C,NULL,NULL,NULL,1,3.3,"A.- Vulnerabilidad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
172,27,2,"¿Cómo hay que valorar una salvaguarda?",NULL,"B.- De forma cualitativa.","C.- En base a su eficacia medida en cómo la salvaguarda está implantada.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,3.3,"A.- Según el coste económico.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
173,27,2,"¿Cuál es la solución ideal para mitigar el riesgo?",NULL,"B.- Reducirlo, mitigarlo. Se limita el impacto.","C.- Transferirlo a otra organización.","D.- Asumirlo. Pasa a contabilizarse como gasto operacional.",A,NULL,NULL,NULL,1,3.4,"A.- Evitarlo.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
174,27,2,"Debe haber un programa de seguridad para:",NULL,"B.- Cada fase del proyecto.","C.- Cada escenario de impacto para dar respuesta.","D.- Cada servicio.",C,NULL,NULL,NULL,1,3.4,"A.- La organización.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
175,27,2,"Los aspectos que definir en la gestión del riesgo son:",NULL,"B.- Las salvaguardas concretas que implantar o mejorar, detallando sus objetivos de calidad, eficacia y eficiencia.","C.- La relación de escenarios de impacto o riesgos que afronta: activos afectados, tipos de activos, amenazas afrontadas, valoración de activos y amenazas y niveles de impacto y riesgo.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,3.4,"A.- Su objetivo genérico.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
176,27,2,"La fase de análisis de riesgos con PILAR comporta las siguientes actividades:",NULL,"B.- Se identifican y valoran las amenazas del sistema.","C.- Se identifica y se valora la efectividad de las salvaguardas.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,3.5,"A.- Se identifican y valoran todos los activos implicados.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
177,27,2,"Señale la respuesta correcta. El coste de las salvaguardas debe ser inferior a:",NULL,"B.- Los beneficios.","C.- La estimación de las pérdidas.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,3.5,"A.- 10 % del valor del sistema a proteger.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
178,27,2,"Los perfiles de seguridad que incorpora la herramienta PILAR son:",NULL,"B.- GDPR.","C.- ENS.","D.- Todas las anteriores son ciertas.",D,NULL,NULL,NULL,1,3.5,"A.- ISO 27002:2013.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
179,27,2,"¿En qué fase se debe realizar un test de penetración a una app web?",NULL,"B.- Desarrollo.","C.- Pruebas.","D.- Producción.",C,NULL,NULL,NULL,1,4.1,"A.- Diseño.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
180,27,2,"La derivación de requisitos de seguridad depende de:",NULL,"B.- Del análisis de riesgos.","C.- Análisis de seguridad del código fuente.","D.- Las opciones A y B.",D,NULL,NULL,NULL,1,4.1,"A.- El modelado de amenazas o casos de abuso.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
181,27,2,"Antes del test de penetración, ¿qué actividades de seguridad hay que llevar a cabo?",NULL,"B.- Modelado de amenazas.","C.- Análisis de seguridad del código fuente.","D.- Todas las opciones anteriores son correctas.",D,NULL,NULL,NULL,1,4.1,"A.- Derivación de requisitos de seguridad.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
182,27,2,"Los web services son un tipo de arquitectura:",NULL,"B.- RIA.","C.- SOA.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,4.2,"A.- Clásica.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
183,27,2,"¿Qué tipo de aplicaciones móviles tienen más limitado el acceso a los dispositivos físicos del móvil?",NULL,"B.- Basadas en navegador.","C.- Híbridas.","D.- Clásicas.",B,NULL,NULL,NULL,1,4.2,"A.- Nativas.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
184,27,2,"En la arquitectura clásica de aplicaciones web, ¿Dónde se genera la capa de presentación?",NULL,"B.- Persistencia.","C.- Servidor de aplicaciones.","D.- SGBD.",C,NULL,NULL,NULL,1,4.2,"A.- Navegador.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
185,27,2,"¿Qué método se suele usar en las arquitecturas de aplicaciones AJAX para comunicación con el servidor?",NULL,"B.- HttpRequest()","C.- xmlRequest().","D.- xmlHttpRequest().",D,NULL,NULL,NULL,1,4.3,"A.- Request().",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
186,27,2,"¿Qué tecnologías usa la arquitectura de aplicaciones AJAX?",NULL,"B.- XML.","C.- HTML.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,4.3,"A.- JavaScript.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
187,27,2,"En la arquitectura RIA de aplicaciones web, ¿dónde se genera la capa de presentación?",NULL,"B.- Persistencia.","C.- Servidor de aplicaciones.","D.- SGBD.",A,NULL,NULL,NULL,1,4.3,"A.- Navegador.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
188,27,2,"¿Qué método HTTP permite conectarse a un servicio situado detrás de un proxy?",NULL,"B.- GET.","C.- POST.","D.- CONNECT.",D,NULL,NULL,NULL,1,4.4,"A.- PUT.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
189,27,2,"¿Qué método HTTP permite obtener solo las cabeceras de la aplicación web?",NULL,"B.- HEAD.","C.- POST.","D.- GET.",B,NULL,NULL,NULL,1,4.4,"A.- PUT.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
190,27,2,"¿Qué método HTTP envía los parámetros en la URL?",NULL,"B.- POST.","C.- PUT.","D.- Todas las anteriores.",A,NULL,NULL,NULL,1,4.4,"A.- GET.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
191,27,2,"¿Cómo se previene XSS?",NULL,"B.- Codificación de la salida.","C.- Validación de entrada mediante consultas parametrizadas.","D.- B y C son correctas.",D,NULL,NULL,NULL,1,5.1,"A.- Test de penetración.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
192,27,2,"¿Qué vectores de entrada se pueden usar para intentar XSS?",NULL,"B.- Campos de formularios.","C.- Cualquier ejecución de un enlace debidamente parametrizado desde cualquier ubicación.","D.- Todas las anteriores son correctas",D,NULL,NULL,NULL,1,5.1,"A.- Enlaces de correos electrónicos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
193,27,2,"¿Cuál es un ejemplo de payload XSS?",NULL,"B.- ‘ OR 1=1#.","C.- C.../../template.ini.","D.- Todas las anteriores.",A,NULL,NULL,NULL,1,5.1,"A.- <script>alert("hacked")</script>.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
194,27,2,"La vulnerabilidad LFI o inclusión de ficheros…",NULL,"B.- Permite autenticarse suplantando a un usuario.","C.- Permite robo de credenciales.","D.- Las opciones A y C son correctas.",D,NULL,NULL,NULL,1,5.2,"A.- Permite acceder a recursos del sistema de ficheros no permitidos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
195,27,2,"¿Qué vectores de entrada se pueden usar para intentar explotar LFI?",NULL,"B.- Campo de un formulario.","C.- Todas las opciones son correctas.","D.- Cualquier ejecución de un enlace debidamente parametrizado desde cualquier ubicación.",C,NULL,NULL,NULL,1,5.2,"A.- Enlaces de correos electrónicos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
196,27,2,"¿Cuál es un ejemplo de payload de RFI?",NULL,"B.- ‘ OR 1=1#","C.- C.../../template.ini","D.- http://localhost/index.php?page = http://google.com/.",D,NULL,NULL,NULL,1,5.2,"A.- <script>alert("hacked")</script>.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
197,27,2,"¿Por qué motivo se puede dar un ataque de suplantación en una aplicación web mediante fijación de sesión?",NULL,"B.- Suplantar a un usuario no es posible a menos que se capture el ID de sesión.","C.- La aplicación web suministra un ID de sesión después de una autenticación correcta de un usuario.","D.- Todas las anteriores son ciertas.",A,NULL,NULL,NULL,1,5.3,"A.- La aplicación web suministra un ID de sesión previo a la autenticación correcta de un usuario.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
198,27,2,"¿Cómo se puede conseguir explotar Server Side Request Forgery?:",NULL,"B.- Ejecutando un enlace contenido en un correo recibido.","C.- Ejecutando un enlace navegando por Internet.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,5.3,"A.- Manipulación de parámetros a través de un formulario.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
199,27,2,"¿Cómo se puede mitigar la vulnerabilidad Server Side Request Forgery?",NULL,"B.- Validación de entrada.","C.- Codificación de la salida.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,5.3,"A.- Consultas parametrizadas.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
200,27,2,"¿Cómo se previene CSRF?",NULL,"B.- Codificación de la salida.","C.- Validación de entrada mediante consultas parametrizadas.","D.- Token anti-CSRF.",D,NULL,NULL,NULL,1,5.4,"A.- Test de penetración.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
201,27,2,"La vulnerabilidad redirección no validada (open redirect):",NULL,"B.- Permite autenticarse suplantando a un usuario.","C.- Permite el robo de credenciales.","D.- Permite redirigir al usuario víctima a un sitio web no esperado.",D,NULL,NULL,NULL,1,5.4,"A.- Permite incluir ficheros remotos de otro servidor no permitidos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
202,27,2,"¿Cuál es un ejemplo de payload de CSRF?",NULL,"B.- ‘ OR 1=1#.","C.- C.../../template.ini.","D.- Ninguna de las anteriores.",D,NULL,NULL,NULL,1,5.4,"A.- <script>alert("hacked")</script>.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
203,27,2,"¿Cómo envía el método Basic las credenciales al servidor de aplicaciones?",NULL,"B.- En claro.","C.- Codificadas Base64.","D.- HASH MD5.",C,NULL,NULL,NULL,1,6.1,"A.- Cifrados.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
204,27,2,"¿Qué ataques puede sufrir Basic?",NULL,"B.- XSS.","C.- CSRF.","D.- RFI.",A,NULL,NULL,NULL,1,6.1,"A.- Repetición.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
205,27,2,"¿Cómo envía Digest las credenciales al servidor de aplicaciones?",NULL,"B.- En claro.","C.- Codificadas en Base64.","D.- HASH MD5.",D,NULL,NULL,NULL,1,6.1,"A.- Cifrados.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
206,27,2,"¿Cómo envía NTLM las credenciales al servidor de aplicaciones?",NULL,"B.- HMAC-MD5.","C.- Codificadas en Base64.","D.- HASH MD5.",B,NULL,NULL,NULL,1,6.2,"A.- Cifrados.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
207,27,2,"¿Qué ataque es típico contra Kerberos?",NULL,"B.- Silver Ticket.","C.- Kerberoasting.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,6.2,"A.- Golden Ticket.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
208,27,2,"NTLM calcula 2 parámetros que son:",NULL,"B.- LMV2 y TNV2.","C.- Solo calcula y envía NTV2.","D.- Todas las anteriores son correctas.",A,NULL,NULL,NULL,1,6.2,"A.- LMV2 y NTV2.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
209,27,2,"OAUTH2 usa:",NULL,"B.- Código de autorización.","C.- La A y la B.","D.- Ticket.",C,NULL,NULL,NULL,1,6.3,"A.- Token de acceso.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
210,27,2,"¿De qué tipo son el token y el código de autorización en OAUTH2?",NULL,"B.- BASIC.","C.- JWT.","D.- HTTP.",C,NULL,NULL,NULL,1,6.3,"A.- DIGEST.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
211,27,2,"¿Dónde se aloja la información del usuario en un JWT?",NULL,"B.- PAYLOAD.","C.- SIGNTURE.","D.- Todas las anteriores son correctas.",B,NULL,NULL,NULL,1,6.3,"A.- HEADER.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
212,27,2,"TLS usa algoritmos como:",NULL,"B.- AES.","C.- SHA-512","D.- Todos los anteriores son correctos.",D,NULL,NULL,NULL,1,6.4,"A.- RSA.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
213,27,2,"La autenticación basada en formularios hace uso de:",NULL,"B.- ID de sesión.","C.- Usuario y contraseña.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,6.4,"A.- Método HTTP POST.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
214,27,2,"¿Qué se recomienda para TLS?",NULL,"B.- Usar AES 256.","C.- Usar RSA 2048.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,6.4,"A.- Además de comprobar el certificado del servidor, requerir la comprobación de un certificado personal al cliente.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
215,27,2,"¿Qué tipo de ataques puede sufrir la autenticación para suplantar un usuario?",NULL,"B.- LFI.","C.- SSRF.","D.- Todos los anteriores son correctos.",A,NULL,NULL,NULL,1,6.5,"A.- Fuerza bruta.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
216,27,2,"¿De qué tipo de ataque previene la implementación de CAPTCHA?",NULL,"B.- LFI.","C.- SQLI.","D.- XSS.",A,NULL,NULL,NULL,1,6.5,"A.- Fuerza bruta.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
217,27,2,"¿Qué medidas se recomiendan para implementar para tener una autenticación más robusta?",NULL,"B.- Combinar distintos métodos de autenticación (algo que se sabe, se tiene o se es).","C.- TLS de cliente requerido para combinar con todos los demás métodos.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,6.5,"A.- Comprobar ruta de certificación en TLS: certificate pinning.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
218,27,2,"¿Cuándo se debe crear el ID de sesión?",NULL,"B.- Después de la autenticación correcta.","C.- En cualquier momento.","D.- No es necesario.",B,NULL,NULL,NULL,1,7.1,"A.- Antes de la autenticación.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
219,27,2,"¿Dónde puede ubicarse el ID de sesión?",NULL,"B.- Parámetro URL.","C.- Parámetro POST.","D.- Todas las anteriores.",D,NULL,NULL,NULL,1,7.1,"A.- Cabecera SET-COOKIE.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
220,27,2,"¿Con qué método de autenticación se crea el ID de sesión?",NULL,"B.- BASIC.","C.- Basado en formularios.","D.- DIGEST.",C,NULL,NULL,NULL,1,7.1,"A.- NTLM.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
221,27,2,"¿Cómo se denomina la base de datos del mecanismo de autorización?",NULL,"B.- Base de datos.","C.- Roles.","D.- Recursos.",A,NULL,NULL,NULL,1,7.2,"A.- Lista de control de acceso.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
222,27,2,"¿Con qué tipo de usuario se ejecuta un proceso relativo a un sitio web o plugin del navegador?",NULL,"B.- Con el usuario del navegador.","C.- Con un token restringido.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,7.2,"A.- Con un usuario cualquiera del sistema operativo.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
223,27,2,"¿Qué se comprueba en la lista de control de acceso para permitir el acceso a un recurso a un usuario?",NULL,"B.- Si es administrador.","C.- Si es administrador no se realizan comprobaciones en la lista de control de acceso.","D.- Ninguna de las anteriores.",A,NULL,NULL,NULL,1,7.2,"A.- Si el usuario posee el rol necesario que requiere el recurso para ser accedido.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
224,27,2,"¿Cuál es un ataque a la autorización?",NULL,"B.- XSS.","C.- LFI.","D.- Todos los anteriores.",D,NULL,NULL,NULL,1,7.3,"A.- TOCTOU.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
225,27,2,"¿Cuál de los siguientes es un mecanismo de defensa para una buena autorización?",NULL,"B.- Separación de roles y tareas.","C.- Administración robusta de permisos.","D.- Todas las anteriores.",D,NULL,NULL,NULL,1,7.3,"A.- Política robusta de contraseñas.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
226,27,2,"¿A qué se debe el TOCTOU?",NULL,"B.- A no bloquear el acceso a los recursos debidamente.","C.- A no tener un identificador de sesión largo.","D.- Las opciones A y B son correctas.",D,NULL,NULL,NULL,1,7.3,"A.- A no diseñar operaciones atómicas.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
227,27,2,"¿Qué no hay que usar para identificar usuarios?",NULL,"B.- Nombres de usuario usando abreviaturas del nombre y apellidos","C.- Opciones A y D.","D.- Direcciones IP, MAC.",C,NULL,NULL,NULL,1,8.1,"A.- Direcciones de correo electrónico.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
228,27,2,"Señala la afirmación incorrecta sobre buenas prácticas de programación:",NULL,"B.- Usar listas negras en lugar de blancas de comprobación.","C.- Revisar el proceso de mantenimiento.","D.- Insistir en el proceso de revisión de código.",B,NULL,NULL,NULL,1,8.1,"A.- Rehusar código que ha sido testeado y probado.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
229,27,2,"Señalar la afirmación incorrecta sobre buenas prácticas de programación:",NULL,"B.- No invocar programas en los que no se confía desde programas en los que se confía.","C.- Asumir que los usuarios no son maliciosos.","D.- Utilizar librerías seguras que generan números aleatorios como random.",C,NULL,NULL,NULL,1,8.1,"A.- No usar en el código nombres relativos de ficheros.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
230,27,2,"La mejor forma de evitar SQL injection es:",NULL,"B.- Validando en el lado del cliente.","C.- Mediante sentencias preparadas de SQL.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,8.2,"A.- Utilizando blacklist antes que whitelist.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
231,27,2,"¿Cuáles son formas de prevención de XSS en el código?",NULL,"B.- Codificación de la salida.","C.- Cabecera XSS-protection y Content Security Policy.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,8.2,"A.- Validación de entrada.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
232,27,2,"¿Cuáles son formas de prevención de HTTP response splitting en el código?",NULL,"B.- Codificación de la salida.","C.- Validación de lista negra.","D.- Todas las anteriores son ciertas.",A,NULL,NULL,NULL,1,8.2,"A.- Validación de entrada para evitar los caracteres CR LF.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
233,27,2,"¿Cómo se pueden evitar vulnerabilidades XXE?",NULL,"B.- Validando los datos de entrada a través del XSD.","C.- No admitiendo definiciones DTD.","D.- Todas las anteriores son ciertas.",D,NULL,NULL,NULL,1,8.3,"A.- Validando los datos de entrada en el código fuente.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
234,27,2,"¿Qué se recomienda a la hora de generar números aleatorios?",NULL,"B.- Usar algoritmos de tipo criptográfico.","C.- Cualquier número lo suficientemente largo > de 14 caracteres es válido.","D.- Todas las anteriores son ciertas.",B,NULL,NULL,NULL,1,8.3,"A.- Usar algoritmos de tipo estadístico.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
235,27,2,"¿Cómo se denomina en Java la función segura de generación de números aleatorios?",NULL,"B.- SecureRamdom().","C.- Ramdom().","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,8.3,"A.- SecRamdom().",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
236,27,2,"Señalar la afirmación incorrecta:",NULL,"B.- El código de terceros y el propio pueden contener vulnerabilidades públicas CVE.","C.- Es necesario comprobar las dependencias de software de terceros para verificar las posibles CVE.","D.- No se puede afirmar una seguridad del 100 % en un código.",A,NULL,NULL,NULL,1,8.4,"A.- No existe inconveniente, desde el punto de vista de la seguridad, en llamar librerías de terceros desde nuestro código, ya que se estima que son seguras.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
237,27,2,"¿Cómo no se debe acceder (mediante autenticación) a una base de datos desde el código?",NULL,"B.- Codificando user/password en el código fuente.","C.- Solicitando user/password al usuario desde la consola y verificar contra la almacenada en un fichero protegido.","D.- Todas las anteriores son ciertas.",B,NULL,NULL,NULL,1,8.4,"A.- Solicitando user/password al usuario desde la consola y verificar contra la almacenada en una BB.DD.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
238,27,2,"¿Qué función hay que usar en lugar de eval()?",NULL,"B.- innertext().","C.- json.parse().","D.- Las herramientas IAST pueden detectar únicamente, bloquear o sanear la petición.",C,NULL,NULL,NULL,1,8.4,"A.- innerhtml().",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
239,27,2,"Señalar la afirmación correcta para evitar Open Redirect:",NULL,"B.- Se debe codificar la salida.","C.- Se debe usar una validación de lista blanca.","D.- Se debe usar una validación en el lado cliente.",C,NULL,NULL,NULL,1,8.5,"A.- Se debe usar sentencias parametrizadas.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
240,27,2,"Señalar la afirmación correcta para evitar CSRF:",NULL,"B.- Se debe codificar la salida.","C.- Se debe usar una validación de lista blanca.","D.- Se debe usar una validación en el lado cliente.",A,NULL,NULL,NULL,1,8.5,"A.- Se debe usar un token anti CSRF.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
241,27,2,"¿A qué corresponde la siguiente línea de código?: req.getParameter("_csrf_token").equals(req.getSession().getAttribute("_csrf_token").",NULL,"B.- Al uso de un identificador de sesión.","C.- A la comprobación de un token anti SSRF.","D.- A la comprobación de un token anti CSRF.",D,NULL,NULL,NULL,1,8.5,"A.- Al uso de sentencias parametrizadas de SQL.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
242,27,2,"¿En qué fase del SSDLC se debe usar una herramienta SAST?",NULL,"B.- Desarrollo.","C.- Producción.","D.- Pruebas.",B,NULL,NULL,NULL,1,9.1,"A.- Diseño.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
243,27,2,"¿En qué fase del SSDLC se debe usar una herramienta DAST?",NULL,"B.- Desarrollo.","C.- Producción.","D.- Pruebas.",D,NULL,NULL,NULL,1,9.1,"A.- Diseño.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
244,27,2,"¿En qué fase del SSDLC se debe usar una herramienta IAST?",NULL,"B.- Desarrollo.","C.- Producción.","D.- Pruebas.",D,NULL,NULL,NULL,1,9.1,"A.- Diseño.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
245,27,2,"¿Qué tipo de análisis puede realizar una herramienta SAST para comprobar las interacciones entre distintas funciones?",NULL,"B.- Interprocedural.","C.- Semántico.","D.- Todos los anteriores.",D,NULL,NULL,NULL,1,9.2,"A.- Intraprocedural.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
246,27,2,"En cuanto a herramientas de análisis de la seguridad SAST, señalar la afirmación falsa:",NULL,"B.- Tienen falsos negativos y falsos positivos.","C.- Algunas pueden analizar código ejecutable.","D.- Todas las anteriores son falsas.",D,NULL,NULL,NULL,1,9.2,"A.- Cubren todo el código de la aplicación excepto las dependencias de terceros.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
247,27,2,"¿Qué se puede hacer con los falsos positivos posibles en el resultado de análisis de una herramienta SAST?",NULL,"B.- No es necesario hacer nada puesto que realmente no son vulnerabilidades.","C.- Este tipo de herramientas no tienen falsos positivos.","D.- Todas las anteriores son ciertas.",A,NULL,NULL,NULL,1,9.2,"A.- Auditar las vulnerabilidades del informe.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
248,27,2,"Señalar la afirmación falsa:",NULL,"B.- Las herramientas RASP se pueden utilizar como firewalls de aplicaciones web de tipo software.","C.- Las herramientas de tipo IAST normalmente no tienen impacto en el rendimiento.","D.- Las herramientas IAST obtienen un informe del análisis de vulnerabilidades.",C,NULL,NULL,NULL,1,9.3,"A.- Las herramientas de análisis de tipo IAST no suelen tener falsos positivos.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
249,27,2,"Las herramientas de tipo IAST pueden instrumentar:",NULL,"B.- Las peticiones y respuestas.","C.- El código ejecutable.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,9.3,"A.- El código fuente.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
250,27,2,"¿Qué tipo de análisis realiza una herramienta de tipo DAST?",NULL,"B.- Sintáctico.","C.- Interprocedural","D.- Intraprodedural.",B,NULL,NULL,NULL,1,9.3,"A.- Semántico.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
251,27,2,"Un WAF detecta y bloquea ataques web usando:",NULL,"B.- Análisis semántico.","C.- No bloquea ataques.","D.- Ninguna de las anteriores.",A,NULL,NULL,NULL,1,10.1,"A.- Expresiones regulares.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
252,27,2,"¿Qué tipo de instalación de un WAF solo detecta y no bloquea un ataque?",NULL,"B.- Proxy reverso.","C.- Pasivo.","D.- Ninguna de las anteriores.",C,NULL,NULL,NULL,1,10.1,"A.- Bridge.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
253,27,2,"¿Qué tipo de instalación es la más recomendable para un WAF?",NULL,"B.- Proxy reverso.","C.- Pasivo.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,10.1,"A.- Bridge.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
254,27,2,"¿Qué valor se recomienda para la cabecera X-FRAME-OPTIONS?",NULL,"B.- HTTPONLY.","C.- LAX.","D.- DENY.",D,NULL,NULL,NULL,1,10.2,"A.- STRICT.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
255,27,2,"¿Qué valor se recomienda para la cabecera CONTENT-SECURITY-POLICY?",NULL,"B.- same origin.","C.- strict.","D.- *.",A,NULL,NULL,NULL,1,10.2,"A.- default-src self.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
256,27,2,"¿Qué valor se recomienda para el parámetro SAMESITE de la cabecera SET-COOKIE?",NULL,"B.- HTTPONLY.","C.- LAX.","D.- DENY.",A,NULL,NULL,NULL,1,10.2,"A.- STRICT.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
257,27,2,"La vulnerabilidad XSS DOM se puede evitar mediante:",NULL,"B.- Validación de entrada.","C.- Cabecera XSS-PROTECTION.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,10.3,"A.- Codificación de la salida.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
258,27,2,"El ataque Javascript hijacking es similar en tecnología AJAX a:",NULL,"B.- CSRF.","C.- SQLI.","D.- Ninguna de las anteriores.",B,NULL,NULL,NULL,1,10.3,"A.- XSS-DOM.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
259,27,2,"¿Cómo se puede saltar/evitar la política del mismo origen?",NULL,"B.- <iframe>…</iframe>.","C.- <img>…</img>.","D.- Todas las anteriores son correctas.",D,NULL,NULL,NULL,1,10.3,"A.- <script>…</script>.",NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
