/*
-- Query: SELECT * FROM preguntas_examen.subtema_topico
LIMIT 0, 1000

-- Date: 2026-02-03 12:49
*/
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (1,1,1);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (2,2,1);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (3,3,1);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (4,4,2);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (5,4,3);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (6,4,5);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (7,4,4);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (8,4,6);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (9,4,7);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (10,4,8);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (11,4,9);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (12,3,102);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (13,3,62);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (14,3,16);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (15,3,61);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (16,3,60);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (17,3,59);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (18,3,58);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (19,3,57);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (20,3,56);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (21,3,55);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (22,3,101);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (23,3,53);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (24,3,11);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (25,3,51);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (26,3,12);
INSERT INTO `` (`ID_SUBTEMA_TOPICO`,`ID_SUBTEMA`,`ID_TOPICO`) VALUES (27,5,103);
