/*
-- Query: SELECT * FROM preguntas_examen.subtema
LIMIT 0, 1000

-- Date: 2026-02-03 12:48
*/
INSERT INTO `` (`ID_SUBTEMA`,`ID_TEMA`,`NOMBRE_SUBTEMA`) VALUES (1,1,'JAVA');
INSERT INTO `` (`ID_SUBTEMA`,`ID_TEMA`,`NOMBRE_SUBTEMA`) VALUES (2,1,'PYTHON');
INSERT INTO `` (`ID_SUBTEMA`,`ID_TEMA`,`NOMBRE_SUBTEMA`) VALUES (3,1,'SQL');
INSERT INTO `` (`ID_SUBTEMA`,`ID_TEMA`,`NOMBRE_SUBTEMA`) VALUES (4,1,'SCRUM');
INSERT INTO `` (`ID_SUBTEMA`,`ID_TEMA`,`NOMBRE_SUBTEMA`) VALUES (5,1,'CIBERSEGURIDAD');
