INSERT INTO TEMA (ID_TEMA,NOMBRE_TEMA) VALUES (1,'INFORMATICA');

INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'JAVA');
INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'PYTHON');
INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'SQL');

INSERT INTO TOPICO (NOMBRE_TOPICO) VALUES ('SINTAXIS');

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (1,1);
INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (2,1);
INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (3,1);

INSERT INTO ORIGEN (ORIGEN) VALUES ('CHATGPT');
INSERT INTO ORIGEN (ORIGEN) VALUES ('UNIR');

#***** 1.- INSERTS DE INFORMATICA*****--
#***** 1.1.- INSERTS DE INFORMATICA > JAVA*****--
#***** 1.1.1- INSERTS DE INFORMATICA > JAVA > SINTAXIS*****--
INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(1,
1,
'¿Cuál de las siguientes opciones es una declaración válida de variable en Java?',
NULL,
NULL,
'A.-int numero = "10";',
'B.-double precio = 25.99;',
'C.-string nombre = "Java";',
'D.-booleano esValido = true;',
'B',
NULL);

INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(1,
1,
'¿Cuál de los siguientes modificadores de acceso permite que una variable o método solo sea accesible dentro de la misma clase?',
NULL,
NULL,
'A.-public',
'B.-protected',
'C.-private',
'D.-default',
'C',
NULL);

INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(1, 1, '¿Qué palabra clave se usa para declarar una constante en Java?', NULL, NULL, 
'A.-const', 
'B.-final', 
'C.-static', 
'D.-let', 
'B', 'En Java, la palabra clave "final" se usa para declarar constantes.'),
(1, 1, '¿Cuál es el tipo de dato predeterminado para números decimales en Java?', NULL, NULL, 
'A.-float', 
'B.-double', 
'C.-int', 
'D.-decimal', 
'B', 'El tipo de dato predeterminado para números decimales en Java es "double".'),
(1, 1, '¿Qué operador se usa para comparar si dos valores son iguales en Java?', NULL, NULL, 
'A.-==', 
'B.-=', 
'C.-equals()', 
'D.-!=', 
'A', 'El operador "==" se usa para comparar valores primitivos en Java. Para objetos, se usa equals().'),
(1, 1, '¿Cuál de los siguientes no es un tipo de dato primitivo en Java?', NULL, NULL, 
'A.-int', 
'B.-String', 
'C.-double', 
'D.-boolean', 
'B', 'String no es un tipo de dato primitivo, es una clase en Java.'),
(1, 1, '¿Cómo se declara un array de enteros en Java?', NULL, NULL, 
'A.-int array[] = new int[5];', 
'B.-array<int> = new int[5];', 
'C.-int[] array = new int(5);', 
'D.-array[] int = new int[5];', 
'A', 'La forma correcta de declarar un array en Java es "int array[] = new int[5];".'),
(1, 1, '¿Cuál es el resultado de la operación 10 / 3 en Java si ambos son enteros?', NULL, NULL, 
'A.-3.33', 
'B.-3', 
'C.-4', 
'D.-Error', 
'B', 'En Java, la división entre enteros devuelve un entero, por lo que 10 / 3 es 3.'),
(1, 1, '¿Qué estructura se usa para manejar excepciones en Java?', NULL, NULL, 
'A.-if-else', 
'B.-switch-case', 
'C.-try-catch', 
'D.-for-each', 
'C', 'El bloque try-catch se usa para manejar excepciones en Java.'),
(1, 1, '¿Cuál de las siguientes opciones es un bucle en Java?', NULL, NULL, 
'A.-loop()', 
'B.-foreach()', 
'C.-do-while', 
'D.-if-else', 
'C', 'do-while es un bucle en Java que se ejecuta al menos una vez antes de evaluar la condición.'),
(1, 1, '¿Cuál es la función principal de la palabra clave "this" en Java?', NULL, NULL, 
'A.-Referenciar la superclase', 
'B.-Referenciar la propia instancia de la clase', 
'C.-Indicar una variable global', 
'D.-Acceder a métodos estáticos', 
'B', 'La palabra clave "this" en Java se usa para referenciar la instancia actual de la clase.'),
(1, 1, '¿Qué palabra clave se usa para heredar una clase en Java?', NULL, NULL, 
'A.-implements', 
'B.-inherits', 
'C.-extends', 
'D.-override', 
'C', 'Para heredar una clase en Java se usa "extends".'),
(1, 1, '¿Qué modificador de acceso permite que un método sea accesible desde cualquier parte del programa?', NULL, NULL, 
'A.-private', 
'B.-protected', 
'C.-default', 
'D.-public', 
'D', 'El modificador "public" permite que un método sea accesible desde cualquier parte del programa.'),
(1, 1, '¿Qué pasa si un método tiene el mismo nombre pero diferente número de parámetros?', NULL, NULL, 
'A.-Error de compilación', 
'B.-Sobrecarga de métodos', 
'C.-Sobrescritura de métodos', 
'D.-No es permitido en Java', 
'B', 'Se llama sobrecarga de métodos (method overloading), donde un método tiene el mismo nombre pero diferentes parámetros.'),
(1, 1, '¿Cómo se llama el proceso de convertir un objeto de una subclase a su superclase?', NULL, NULL, 
'A.-Downcasting', 
'B.-Upcasting', 
'C.-Polimorfismo', 
'D.-Instanciación', 
'B', 'Upcasting es el proceso de convertir un objeto de una subclase a su superclase en Java.'),
(1, 1, '¿Cuál es el valor predeterminado de un atributo de instancia de tipo int en Java?', NULL, NULL, 
'A.-null', 
'B.-0', 
'C.-1', 
'D.-No tiene valor por defecto', 
'B', 'Los atributos de tipo int en Java tienen un valor predeterminado de 0.'),
(1, 1, '¿Cuál de los siguientes no es un operador lógico en Java?', NULL, NULL, 
'A.-&&', 
'B.-||', 
'C.-!', 
'D.-%%', 
'D', 'El operador "%%" no existe en Java. Los operadores lógicos válidos son &&, || y !.'),
(1, 1, '¿Qué tipo de dato devuelve un método con la firma "public void metodo()"?', NULL, NULL, 
'A.-int', 
'B.-void', 
'C.-null', 
'D.-No devuelve nada', 
'B', 'El tipo "void" indica que el método no devuelve ningún valor.'),
(1, 1, '¿Qué palabra clave se usa para definir una interfaz en Java?', NULL, NULL, 
'A.-abstract', 
'B.-class', 
'C.-interface', 
'D.-implements', 
'C', 'La palabra clave "interface" se usa para definir interfaces en Java.'),
(1, 1, '¿Cuál es la salida de System.out.println(2 + "3"); en Java?', NULL, NULL, 
'A.-5', 
'B.-23', 
'C.-Error de compilación', 
'D.-Ninguna de las anteriores', 
'B', 'En Java, si se concatena un número con un string, el número se convierte en string.'),
(1, 1, '¿Qué método se ejecuta automáticamente cuando se instancia una clase en Java?', NULL, NULL, 
'A.-run()', 
'B.-start()', 
'C.-constructor', 
'D.-initialize()', 
'C', 'El constructor es el método que se ejecuta automáticamente al instanciar una clase en Java.');

#***** 1.2.- INSERTS DE INFORMATICA > PYTHON*****--
#***** 1.2.1- INSERTS DE INFORMATICA > PYTHON > SINTAXIS*****--
INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(2, 1, '¿Cuál es la función de la instrucción "def" en Python?', NULL, NULL, 
'A.-Definir una clase', 
'B.-Definir una función', 
'C.-Importar un módulo', 
'D.-Declarar una variable', 
'B', 'La palabra clave "def" en Python se usa para definir funciones.'),
(2, 1, '¿Qué operador se usa para calcular el módulo de una división en Python?', NULL, NULL, 
'A.-%', 
'B.-//', 
'C.-/', 
'D.-*', 
'A', 'El operador "%" se usa para obtener el residuo de una división en Python.'),
(2, 1, '¿Cómo se declara una lista en Python?', NULL, NULL, 
'A.-list = {1,2,3}', 
'B.-list = [1,2,3]', 
'C.-list = (1,2,3)', 
'D.-list = <1,2,3>', 
'B', 'Las listas en Python se declaran con corchetes [].'),
(2, 1, '¿Cuál de los siguientes no es un tipo de dato en Python?', NULL, NULL, 
'A.-int', 
'B.-float', 
'C.-char', 
'D.-bool', 
'C', 'Python no tiene un tipo de dato "char"; los caracteres son cadenas de un solo carácter.'),
(2, 1, '¿Cuál es la forma correcta de escribir un comentario en Python?', NULL, NULL, 
'A.-// Este es un comentario', 
'B.-# Este es un comentario', 
'C.-<!-- Este es un comentario -->', 
'D.-/* Este es un comentario */', 
'B', 'En Python, los comentarios de una sola línea se escriben con "#".'),
(2, 1, '¿Qué función se usa para obtener la longitud de una lista en Python?', NULL, NULL, 
'A.-length()', 
'B.-size()', 
'C.-count()', 
'D.-len()', 
'D', 'La función "len()" se usa para obtener la longitud de una lista en Python.'),
(2, 1, '¿Cuál es la forma correcta de abrir un archivo en Python?', NULL, NULL, 
'A.-file = open("archivo.txt", "r")', 
'B.-file = read("archivo.txt")', 
'C.-file.open("archivo.txt")', 
'D.-file = openFile("archivo.txt")', 
'A', 'La función "open()" se usa para abrir archivos en Python.'),
(2, 1, '¿Cuál es el resultado de print(2 ** 3) en Python?', NULL, NULL, 
'A.-6', 
'B.-8', 
'C.-9', 
'D.-Error', 
'B', 'El operador "**" en Python se usa para exponentes, por lo que 2 ** 3 es 8.'),
(2, 1, '¿Cuál es el valor de la expresión bool([]) en Python?', NULL, NULL, 
'A.-True', 
'B.-False', 
'C.-Error', 
'D.-None', 
'B', 'Las listas vacías en Python se evalúan como False en un contexto booleano.'),
(2, 1, '¿Cómo se define una variable global dentro de una función en Python?', NULL, NULL, 
'A.-global variable', 
'B.-def global variable', 
'C.-set global variable', 
'D.-var global', 
'A', 'Para definir una variable global dentro de una función en Python, se usa la palabra clave "global".'),
(2, 1, '¿Qué método se usa para convertir un string en minúsculas en Python?', NULL, NULL, 
'A.-toLowerCase()', 
'B.-lower()', 
'C.-small()', 
'D.-downcase()', 
'B', 'El método "lower()" convierte un string a minúsculas en Python.'),
(2, 1, '¿Qué tipo de estructura de control es "elif" en Python?', NULL, NULL, 
'A.-Condicional', 
'B.-Bucle', 
'C.-Función', 
'D.-Excepción', 
'A', 'El "elif" en Python se usa en estructuras condicionales.'),
(2, 1, '¿Cuál de los siguientes métodos se usa para agregar un elemento a una lista en Python?', NULL, NULL, 
'A.-add()', 
'B.-insert()', 
'C.-append()', 
'D.-push()', 
'C', 'El método "append()" agrega un elemento al final de una lista en Python.'),
(2, 1, '¿Qué devuelve la función type(5) en Python?', NULL, NULL, 
'A.-"int"', 
'B.-<class ''int''>', 
'C.-"integer"', 
'D.-Error', 
'B', 'La función "type()" devuelve el tipo de dato de un valor en Python.'),
(2, 1, '¿Cuál es la forma correcta de definir un diccionario en Python?', NULL, NULL, 
'A.-dict = [key1: value1, key2: value2]', 
'B.-dict = {key1: value1, key2: value2}', 
'C.-dict = (key1: value1, key2: value2)', 
'D.-dict = <key1: value1, key2: value2>', 
'B', 'Los diccionarios en Python se definen con llaves {}.'),
(2, 1, '¿Cuál es la función de la instrucción "import" en Python?', NULL, NULL, 
'A.-Importar módulos', 
'B.-Definir variables', 
'C.-Declarar funciones', 
'D.-Ejecutar código externo', 
'A', 'La palabra clave "import" se usa para importar módulos en Python.'),
(2, 1, '¿Cuál es la función de la palabra clave "pass" en Python?', NULL, NULL, 
'A.-Terminar un bucle', 
'B.-Ignorar una línea de código', 
'C.-Definir una función vacía', 
'D.-Cerrar un archivo', 
'C', 'La palabra clave "pass" se usa como marcador de posición en funciones o clases vacías.'),
(2, 1, '¿Cuál es la salida de print("Python"[::-1])?', NULL, NULL, 
'A.-"nohtyP"', 
'B.-"Python"', 
'C.-Error', 
'D.-None', 
'A', 'El operador de slicing "[::-1]" invierte una cadena en Python.');

#***** 1.3.- INSERTS DE INFORMATICA > SQL*****--
#***** 1.3.1- INSERTS DE INFORMATICA > SQL > SINTAXIS*****--
INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(3, 1, '¿Qué instrucción se usa para seleccionar todos los registros de una tabla en SQL?', NULL, NULL, 
'A.-GET * FROM tabla', 
'B.-SELECT * FROM tabla', 
'C.-SHOW * FROM tabla', 
'D.-FETCH * FROM tabla', 
'B', 'La instrucción correcta para seleccionar todos los registros es "SELECT * FROM tabla".'),
(3, 1, '¿Qué cláusula se usa para filtrar resultados en una consulta SQL?', NULL, NULL, 
'A.-FILTER', 
'B.-WHERE', 
'C.-HAVING', 
'D.-ORDER BY', 
'B', 'La cláusula "WHERE" se usa para filtrar registros en una consulta SQL.'),
(3, 1, '¿Cuál de los siguientes comandos se usa para eliminar una tabla en SQL?', NULL, NULL, 
'A.-REMOVE TABLE nombre_tabla', 
'B.-DELETE TABLE nombre_tabla', 
'C.-DROP TABLE nombre_tabla', 
'D.-CLEAR TABLE nombre_tabla', 
'C', 'El comando "DROP TABLE" elimina completamente una tabla y sus datos.'),
(3, 1, '¿Cómo se renombra una tabla en SQL?', NULL, NULL, 
'A.-MODIFY TABLE tabla RENAME TO nueva_tabla', 
'B.-CHANGE TABLE tabla TO nueva_tabla', 
'C.-ALTER TABLE tabla RENAME TO nueva_tabla', 
'D.-RENAME TABLE tabla TO nueva_tabla', 
'D', 'El comando "RENAME TABLE nombre_actual TO nuevo_nombre" cambia el nombre de una tabla en SQL.'),
(3, 1, '¿Cuál de las siguientes opciones es una restricción de SQL?', NULL, NULL, 
'A.-PRIMARY KEY', 
'B.-CHECK', 
'C.-NOT NULL', 
'D.-Todas las anteriores', 
'D', 'Las restricciones en SQL incluyen PRIMARY KEY, CHECK, NOT NULL, y otras.'),
(3, 1, '¿Qué comando se usa para actualizar datos en una tabla en SQL?', NULL, NULL, 
'A.-CHANGE', 
'B.-UPDATE', 
'C.-MODIFY', 
'D.-SET', 
'B', 'El comando "UPDATE" se usa para modificar registros existentes en una tabla.'),
(3, 1, '¿Cómo se obtiene el número total de registros en una tabla en SQL?', NULL, NULL, 
'A.-COUNT(*)', 
'B.-SUM(*)', 
'C.-TOTAL(*)', 
'D.-LENGTH(*)', 
'A', 'La función "COUNT(*)" devuelve el número total de registros en una tabla.'),
(3, 1, '¿Cuál de las siguientes cláusulas se usa para ordenar los resultados de una consulta SQL?', NULL, NULL, 
'A.-SORT BY', 
'B.-ORDER BY', 
'C.-GROUP BY', 
'D.-RANK BY', 
'B', 'La cláusula "ORDER BY" ordena los resultados de una consulta SQL.'),
(3, 1, '¿Cómo se seleccionan registros únicos en SQL?', NULL, NULL, 
'A.-SELECT DISTINCT columna FROM tabla', 
'B.-SELECT UNIQUE columna FROM tabla', 
'C.-SELECT DIFFERENT columna FROM tabla', 
'D.-SELECT DISTINCTIVE columna FROM tabla', 
'A', 'La palabra clave "DISTINCT" permite seleccionar valores únicos en SQL.'),
(3, 1, '¿Cuál es el propósito de la cláusula GROUP BY en SQL?', NULL, NULL, 
'A.-Ordenar los registros', 
'B.-Agrupar registros con valores en común', 
'C.-Eliminar registros duplicados', 
'D.-Filtrar datos en una consulta', 
'B', 'La cláusula "GROUP BY" se usa para agrupar filas que tienen valores idénticos en columnas específicas.'),
(3, 1, '¿Cuál es la función de la cláusula HAVING en SQL?', NULL, NULL, 
'A.-Filtrar resultados después de agrupar con GROUP BY', 
'B.-Ordenar los datos en una consulta', 
'C.-Eliminar registros duplicados', 
'D.-Limitar el número de registros en una consulta', 
'A', 'La cláusula "HAVING" se usa para filtrar datos después de aplicar "GROUP BY".'),
(3, 1, '¿Cuál es la diferencia entre DELETE y TRUNCATE en SQL?', NULL, NULL, 
'A.-DELETE borra registros individualmente, TRUNCATE borra todos sin registro en logs', 
'B.-DELETE elimina la tabla completa, TRUNCATE solo los registros', 
'C.-DELETE y TRUNCATE son sinónimos', 
'D.-DELETE solo borra algunos registros, TRUNCATE borra la base de datos', 
'A', 'DELETE permite eliminar registros específicos con WHERE, mientras que TRUNCATE borra toda la tabla de manera rápida y sin registrar cada eliminación individualmente.'),
(3, 1, '¿Cómo se crea una nueva base de datos en SQL?', NULL, NULL, 
'A.-NEW DATABASE nombre', 
'B.-CREATE DATABASE nombre', 
'C.-ADD DATABASE nombre', 
'D.-MAKE DATABASE nombre', 
'B', 'El comando "CREATE DATABASE nombre" se usa para crear una nueva base de datos.'),
(3, 1, '¿Cuál es el comando para agregar una nueva columna a una tabla en SQL?', NULL, NULL, 
'A.-ADD COLUMN', 
'B.-ALTER TABLE ... ADD COLUMN', 
'C.-INSERT COLUMN', 
'D.-MODIFY TABLE ... ADD COLUMN', 
'B', 'El comando "ALTER TABLE tabla ADD COLUMN nombre_columna tipo_dato" se usa para añadir columnas a una tabla existente.'),
(3, 1, '¿Cómo se elimina un solo registro de una tabla en SQL?', NULL, NULL, 
'A.-DELETE FROM tabla WHERE id = valor', 
'B.-REMOVE FROM tabla WHERE id = valor', 
'C.-DROP FROM tabla WHERE id = valor', 
'D.-ERASE FROM tabla WHERE id = valor', 
'A', 'El comando correcto es "DELETE FROM tabla WHERE id = valor".'),
(3, 1, '¿Qué comando se usa para hacer una copia de seguridad de una base de datos en SQL?', NULL, NULL, 
'A.-BACKUP DATABASE nombre', 
'B.-EXPORT DATABASE nombre', 
'C.-SAVE DATABASE nombre', 
'D.-DUMP DATABASE nombre', 
'A', 'El comando "BACKUP DATABASE nombre" se usa para crear una copia de seguridad en SQL.'),
(3, 1, '¿Cuál es la estructura básica de una consulta SQL?', NULL, NULL, 
'A.-GET columna FROM tabla', 
'B.-SELECT columna FROM tabla', 
'C.-FETCH columna FROM tabla', 
'D.-SHOW columna FROM tabla', 
'B', 'La estructura básica de una consulta SQL es "SELECT columna FROM tabla".'),
(3, 1, '¿Qué hace la cláusula LIMIT en una consulta SQL?', NULL, NULL, 
'A.-Limita el número de registros devueltos', 
'B.-Ordena los registros de la consulta', 
'C.-Agrupa los datos en la consulta', 
'D.-Elimina registros duplicados', 
'A', 'La cláusula "LIMIT" restringe la cantidad de registros devueltos por una consulta SQL.'),
(3, 1, '¿Cómo se combinan registros de dos tablas en SQL?', NULL, NULL, 
'A.-USING JOIN', 
'B.-COMBINE TABLES', 
'C.-MERGE TABLES', 
'D.-USING UNION', 
'D', 'El operador "UNION" combina los resultados de dos consultas SQL.'),
(3, 1, '¿Qué operador se usa para buscar un patrón de texto en SQL?', NULL, NULL, 
'A.-LIKE', 
'B.-FIND', 
'C.-MATCH', 
'D.-SEARCH', 
'A', 'El operador "LIKE" permite buscar patrones en columnas de texto en SQL.');

COMMIT;