INSERT INTO TEMA (ID_TEMA,NOMBRE_TEMA) VALUES (1,'INFORMATICA');

INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'JAVA');
INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'PYTHON');
INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'SQL');
INSERT INTO SUBTEMA (ID_TEMA,NOMBRE_SUBTEMA) VALUES (1,'SCRUM');
SELECT * FROM SUBTEMA;
SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM';







INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (1,1);
INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (2,1);
INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (3,1);
DELETE FROM SUBTEMA_TOPICO WHERE ID_SUBTEMA_TOPICO = 6;

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'HISTORIAS DE USUARIO'));

SELECT * FROM SUBTEMA_TOPICO;


INSERT INTO ORIGEN (ORIGEN) VALUES ('CHATGPT');
INSERT INTO ORIGEN (ORIGEN) VALUES ('UNIR');


