SELECT
	P.ID_PREGUNTA,
	P.PREGUNTA,
	P.IMAGEN_PREGUNTA,
	P.RESPUESTA_A,
    P.IMAGEN_RESP_A,
	P.RESPUESTA_B,
    P.IMAGEN_RESP_B,
	P.RESPUESTA_C,
    P.IMAGEN_RESP_C,
	P.RESPUESTA_D,
    P.IMAGEN_RESP_D,
	P.RESPUESTA_CORRECTA,
	ORI.ORIGEN,
	S.NOMBRE_SUBTEMA,
	T.NOMBRE_TEMA,
	TOP.NOMBRE_TOPICO,
    M.NOMBRE_MATERIA,
    P.UNIDAD
FROM preguntas P 
JOIN origen ORI ON ORI.ID_ORIGEN = P.ID_ORIGEN
JOIN subtema_topico ST ON ST.ID_SUBTEMA_TOPICO = P.ID_SUBTEMA_TOPICO
JOIN subtema S ON ST.ID_SUBTEMA = S.ID_SUBTEMA
JOIN TEMA T ON T.ID_TEMA = S.ID_TEMA
JOIN TOPICO TOP ON TOP.ID_TOPICO = ST.ID_TOPICO
LEFT JOIN MATERIA M ON P.ID_MATERIA = M.ID_MATERIA;

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PREGUNTAS'
  AND TABLE_SCHEMA = 'PREGUNTAS_EXAMEN';
  
SELECT * FROM PREGUNTAS;

SELECT * FROM SUBTEMA;

SELECT ST.ID_SUBTEMA_TOPICO, 
		S.NOMBRE_SUBTEMA,
        T.NOMBRE_TOPICO
FROM SUBTEMA_TOPICO ST
	JOIN SUBTEMA S ON S.ID_SUBTEMA = ST.ID_SUBTEMA
    JOIN TOPICO T ON T.ID_TOPICO = ST.ID_TOPICO;
    

SELECT ST.ID_SUBTEMA_TOPICO, 
		S.NOMBRE_SUBTEMA,
        T.NOMBRE_TOPICO
FROM SUBTEMA_TOPICO ST
	JOIN SUBTEMA S ON S.ID_SUBTEMA = ST.ID_SUBTEMA
    JOIN TOPICO T ON T.ID_TOPICO = ST.ID_TOPICO
WHERE S.NOMBRE_SUBTEMA = 'CIBERSEGURIDAD'
AND T.NOMBRE_TOPICO = 'CIBERSEGURIDAD';
    
    
###################
# INSERTS
INSERT INTO SUBTEMA (ID_TEMA, NOMBRE_SUBTEMA) VALUES (1, 'CIBERSEGURIDAD');

INSERT INTO TOPICO (NOMBRE_TOPICO) VALUES ('CIBERSEGURIDAD');

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
	(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'CIBERSEGURIDAD'),
    (SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'CIBERSEGURIDAD')
    );
    #ISNERTAR CUANDO SON DE UNIR
INSERT INTO PREGUNTAS (
	ID_SUBTEMA_TOPICO, 
    ID_ORIGEN,
    PREGUNTA,
    RESPUESTA_A,
    RESPUESTA_B,
    RESPUESTA_C,
    RESPUESTA_D,
    RESPUESTA_CORRECTA,
    ID_MATERIA,
    UNIDAD) 
	VALUES (
    27,
    2,
    'El coste de realizar un ataque se denomina:',
    'Coste de ataque.',
    'Cost to break.',
    'Cost to fix.',
    'Coste de reconstrucción.',
    'B',
    1,
    '1.1');
    
    select ST.ID_SUBTEMA_TOPICO, S.NOMBRE_SUBTEMA, T.NOMBRE_TOPICO from subtema_topico ST
   join subtema S on S.ID_SUBTEMA = ST.ID_SUBTEMA
   join topico T on T.ID_TOPICO = ST.ID_TOPICO
   where ST.ID_SUBTEMA = 3;
   
   
   #Sacar IDS de un tema subtema topico en especial
   select * from preguntas;
   select * from subtema;
   select * from tema;
   select * from topico;
   select * from subtema_topico;
   select * from origen;
   
   #Union Tema Subtema
   select * from tema t
   join subtema st on st.ID_TEMA = t.ID_TEMA;  
   
   # union subtema topico
   select sto.ID_SUBTEMA_TOPICO, NOMBRE_SUBTEMA, NOMBRE_TOPICO from subtema_topico sto
   join subtema st on sto.ID_SUBTEMA = st.ID_SUBTEMA
   join topico t on sto.ID_TOPICO = t.ID_TOPICO;
   
   select * from preguntas where ID_SUBTEMA_TOPICO in (27);