SELECT * FROM ORIGEN;
SELECT * FROM TEMA;
SELECT * FROM SUBTEMA;
SELECT * FROM TOPICO;
SELECT * FROM SUBTEMA_TOPICO;
SELECT * FROM PREGUNTAS;

#MUESTRA TODOS LOS ID_SUBTEMA_TOPICO Y SUS NOMBRES
SELECT ST.ID_SUBTEMA_TOPICO,ST.ID_SUBTEMA,ST.ID_TOPICO,
SU.NOMBRE_SUBTEMA, TOP.NOMBRE_TOPICO
FROM SUBTEMA_TOPICO ST
JOIN SUBTEMA SU ON ST.ID_SUBTEMA = SU.ID_SUBTEMA 
JOIN TOPICO TOP ON ST.ID_TOPICO = TOP.ID_TOPICO
WHERE SU.NOMBRE_SUBTEMA = 'SQL';

#SELECCIONAR PREGUNTAS POR NOMBRE SUBTEMA Y TOPICO
SELECT * FROM PREGUNTAS
WHERE ID_SUBTEMA_TOPICO = (SELECT ID_SUBTEMA_TOPICO FROM SUBTEMA_TOPICO 
WHERE ID_SUBTEMA = (SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM') 
AND ID_TOPICO = (SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'GRAFICAS DE SCRUM'));

SELECT * FROM PREGUNTAS
WHERE ID_SUBTEMA_TOPICO = (SELECT ID_SUBTEMA_TOPICO FROM SUBTEMA_TOPICO 
WHERE ID_SUBTEMA = (SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM') 
AND ID_TOPICO = (SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'GRAFICAS DE SCRUM'));


SELECT * FROM TOPICO WHERE ID_TOPICO = (SELECT ID_TOPICO FROM SUBTEMA_TOPICO WHERE ID_SUBTEMA = 1);
SELECT ID_TOPICO FROM SUBTEMA_TOPICO WHERE ID_SUBTEMA = 1;

SELECT * FROM SUBTEMA; 
SELECT ID_SUBTEMA FROM SUBTEMA WHERE ESTATUS = 'A';
SELECT * FROM SUBTEMA_TOPICO WHERE ID_SUBTEMA IN (SELECT ID_SUBTEMA FROM SUBTEMA WHERE ESTATUS = 'A');

SELECT * FROM PREGUNTAS WHERE ID_SUBTEMA_TOPICO IN 
(SELECT ID_SUBTEMA_TOPICO FROM SUBTEMA_TOPICO WHERE ID_SUBTEMA IN 
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE ESTATUS = 'A'));



SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'FASES' ;
SELECT *  FROM SUBTEMA_TOPICO WHERE ID_TOPICO = (SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'FASES');


COMMIT;

SELECT * FROM PREGUNTAS WHERE ID_PREGUNTA = 1;

SELECT * FROM PREGUNTAS WHERE ID_SUBTEMA_TOPICO = 5;

select * from preguntas where pregunta like('%¿Cómo se elimina un elemento de una lista en Python?%');
delete from preguntas where ID_PREGUNTA = 38;
commit;
SELECT COUNT(*) AS TOTAL_PREGUNTAS FROM PREGUNTAS;