SELECT * FROM TEMA;
SELECT * FROM SUBTEMA;
SELECT * FROM TOPICO;
SELECT * FROM PREGUNTAS;

SELECT TM.ID_TEMA, TM.NOMBRE_TEMA,
ST.ID_SUBTEMA, ST.NOMBRE_SUBTEMA,
TOP.ID_TOPICO, TOP.NOMBRE_TOPICO,
PR.PREGUNTA, PR.RESPUESTA_A, PR.RESPUESTA_B, PR.RESPUESTA_C, PR.RESPUESTA_D, PR.RESPUESTA_CORRECTA
FROM TEMA TM
JOIN SUBTEMA ST
ON TM.ID_TEMA = ST.ID_TEMA
JOIN TOPICO TOP
ON TOP.ID_SUBTEMA = ST.ID_SUBTEMA
JOIN PREGUNTAS PR
ON TOP.ID_TOPICO = PR.ID_TOPICO;

ROLLBACK;
COMMIT;





