--CREACION DE TABLAS
CREATE TABLE TEMA (
ID_TEMA NUMBER PRIMARY KEY,
NOMBRE_TEMA VARCHAR2(100) UNIQUE NOT NULL);

CREATE TABLE SUBTEMA (
ID_SUBTEMA NUMBER PRIMARY KEY,
ID_TEMA NUMBER NOT NULL,
NOMBRE_SUBTEMA VARCHAR2(150) NOT NULL);

CREATE TABLE TOPICO (
ID_TOPICO NUMBER PRIMARY KEY,
ID_SUBTEMA NUMBER NOT NULL, 
NOMBRE_TOPICO VARCHAR2(150) NOT NULL);

CREATE TABLE PREGUNTAS (
ID_PREGUNTA NUMBER PRIMARY KEY,
ID_TOPICO NUMBER NOT NULL, 
PREGUNTA VARCHAR2(500) NOT NULL, 
RESPUESTA_A VARCHAR2(500) NOT NULL,
RESPUESTA_B VARCHAR2(500), 
RESPUESTA_C VARCHAR2(500), 
RESPUESTA_D VARCHAR2(500), 
RESPUESTA_CORRECTA VARCHAR2(1) NOT NULL);

DROP TABLE TEMA;
DROP TABLE SUBTEMA;
DROP TABLE TOPICO;
DROP TABLE PREGUNTAS;