#CREACION DE TABLAS
CREATE TABLE ORIGEN (
ID_ORIGEN INT PRIMARY KEY AUTO_INCREMENT,
ORIGEN VARCHAR(100));

CREATE TABLE TEMA (
ID_TEMA INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_TEMA VARCHAR(100) UNIQUE NOT NULL);

CREATE TABLE SUBTEMA (
ID_SUBTEMA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_TEMA INT NOT NULL,
NOMBRE_SUBTEMA VARCHAR(150) NOT NULL);

CREATE TABLE TOPICO (
ID_TOPICO INT PRIMARY KEY AUTO_INCREMENT, 
NOMBRE_TOPICO VARCHAR(150) NOT NULL);

CREATE TABLE SUBTEMA_TOPICO(
ID_SUBTEMA_TOPICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ID_SUBTEMA INT NOT NULL,
ID_TOPICO INT NOT NULL);

CREATE TABLE PREGUNTAS (
ID_PREGUNTA INT AUTO_INCREMENT PRIMARY KEY,
ID_SUBTEMA_TOPICO INT NOT NULL,
ID_ORIGEN INT NOT NULL, 
PREGUNTA VARCHAR(500) NOT NULL UNIQUE,
IMAGEN TEXT,
RUTA_ARCHIVO VARCHAR (500), 
RESPUESTA_A VARCHAR(500) NOT NULL,
RESPUESTA_B VARCHAR(500) NOT NULL, 
RESPUESTA_C VARCHAR(500), 
RESPUESTA_D VARCHAR(500), 
RESPUESTA_CORRECTA VARCHAR(1) NOT NULL,
EXPLICACION TEXT);

DROP TABLE TEMA;
DROP TABLE SUBTEMA;
DROP TABLE TOPICO;
DROP TABLE SUBTEMA_TOPICO;
DROP TABLE PREGUNTAS;
DROP TABLE ORIGEN;