#***** 1.3.- INSERTS DE INFORMATICA > SQL*****--
#***** 1.3.1- INSERTS DE INFORMATICA > SQL > SINTAXIS*****--
INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(3, 1, '¿Qué instrucción se usa para seleccionar todos los registros de una tabla en SQL?', NULL, NULL, 
'A.-GET * FROM tabla', 
'B.-SELECT * FROM tabla', 
'C.-SHOW * FROM tabla', 
'D.-FETCH * FROM tabla', 
'B', 'La instrucción correcta para seleccionar todos los registros es "SELECT * FROM tabla".'),
(3, 1, '¿Qué cláusula se usa para filtrar resultados en una consulta SQL?', NULL, NULL, 
'A.-FILTER', 
'B.-WHERE', 
'C.-HAVING', 
'D.-ORDER BY', 
'B', 'La cláusula "WHERE" se usa para filtrar registros en una consulta SQL.'),
(3, 1, '¿Cuál de los siguientes comandos se usa para eliminar una tabla en SQL?', NULL, NULL, 
'A.-REMOVE TABLE nombre_tabla', 
'B.-DELETE TABLE nombre_tabla', 
'C.-DROP TABLE nombre_tabla', 
'D.-CLEAR TABLE nombre_tabla', 
'C', 'El comando "DROP TABLE" elimina completamente una tabla y sus datos.'),
(3, 1, '¿Cómo se renombra una tabla en SQL?', NULL, NULL, 
'A.-MODIFY TABLE tabla RENAME TO nueva_tabla', 
'B.-CHANGE TABLE tabla TO nueva_tabla', 
'C.-ALTER TABLE tabla RENAME TO nueva_tabla', 
'D.-RENAME TABLE tabla TO nueva_tabla', 
'D', 'El comando "RENAME TABLE nombre_actual TO nuevo_nombre" cambia el nombre de una tabla en SQL.'),
(3, 1, '¿Cuál de las siguientes opciones es una restricción de SQL?', NULL, NULL, 
'A.-PRIMARY KEY', 
'B.-CHECK', 
'C.-NOT NULL', 
'D.-Todas las anteriores', 
'D', 'Las restricciones en SQL incluyen PRIMARY KEY, CHECK, NOT NULL, y otras.'),
(3, 1, '¿Qué comando se usa para actualizar datos en una tabla en SQL?', NULL, NULL, 
'A.-CHANGE', 
'B.-UPDATE', 
'C.-MODIFY', 
'D.-SET', 
'B', 'El comando "UPDATE" se usa para modificar registros existentes en una tabla.'),
(3, 1, '¿Cómo se obtiene el número total de registros en una tabla en SQL?', NULL, NULL, 
'A.-COUNT(*)', 
'B.-SUM(*)', 
'C.-TOTAL(*)', 
'D.-LENGTH(*)', 
'A', 'La función "COUNT(*)" devuelve el número total de registros en una tabla.'),
(3, 1, '¿Cuál de las siguientes cláusulas se usa para ordenar los resultados de una consulta SQL?', NULL, NULL, 
'A.-SORT BY', 
'B.-ORDER BY', 
'C.-GROUP BY', 
'D.-RANK BY', 
'B', 'La cláusula "ORDER BY" ordena los resultados de una consulta SQL.'),
(3, 1, '¿Cómo se seleccionan registros únicos en SQL?', NULL, NULL, 
'A.-SELECT DISTINCT columna FROM tabla', 
'B.-SELECT UNIQUE columna FROM tabla', 
'C.-SELECT DIFFERENT columna FROM tabla', 
'D.-SELECT DISTINCTIVE columna FROM tabla', 
'A', 'La palabra clave "DISTINCT" permite seleccionar valores únicos en SQL.'),
(3, 1, '¿Cuál es el propósito de la cláusula GROUP BY en SQL?', NULL, NULL, 
'A.-Ordenar los registros', 
'B.-Agrupar registros con valores en común', 
'C.-Eliminar registros duplicados', 
'D.-Filtrar datos en una consulta', 
'B', 'La cláusula "GROUP BY" se usa para agrupar filas que tienen valores idénticos en columnas específicas.'),
(3, 1, '¿Cuál es la función de la cláusula HAVING en SQL?', NULL, NULL, 
'A.-Filtrar resultados después de agrupar con GROUP BY', 
'B.-Ordenar los datos en una consulta', 
'C.-Eliminar registros duplicados', 
'D.-Limitar el número de registros en una consulta', 
'A', 'La cláusula "HAVING" se usa para filtrar datos después de aplicar "GROUP BY".'),
(3, 1, '¿Cuál es la diferencia entre DELETE y TRUNCATE en SQL?', NULL, NULL, 
'A.-DELETE borra registros individualmente, TRUNCATE borra todos sin registro en logs', 
'B.-DELETE elimina la tabla completa, TRUNCATE solo los registros', 
'C.-DELETE y TRUNCATE son sinónimos', 
'D.-DELETE solo borra algunos registros, TRUNCATE borra la base de datos', 
'A', 'DELETE permite eliminar registros específicos con WHERE, mientras que TRUNCATE borra toda la tabla de manera rápida y sin registrar cada eliminación individualmente.'),
(3, 1, '¿Cómo se crea una nueva base de datos en SQL?', NULL, NULL, 
'A.-NEW DATABASE nombre', 
'B.-CREATE DATABASE nombre', 
'C.-ADD DATABASE nombre', 
'D.-MAKE DATABASE nombre', 
'B', 'El comando "CREATE DATABASE nombre" se usa para crear una nueva base de datos.'),
(3, 1, '¿Cuál es el comando para agregar una nueva columna a una tabla en SQL?', NULL, NULL, 
'A.-ADD COLUMN', 
'B.-ALTER TABLE ... ADD COLUMN', 
'C.-INSERT COLUMN', 
'D.-MODIFY TABLE ... ADD COLUMN', 
'B', 'El comando "ALTER TABLE tabla ADD COLUMN nombre_columna tipo_dato" se usa para añadir columnas a una tabla existente.'),
(3, 1, '¿Cómo se elimina un solo registro de una tabla en SQL?', NULL, NULL, 
'A.-DELETE FROM tabla WHERE id = valor', 
'B.-REMOVE FROM tabla WHERE id = valor', 
'C.-DROP FROM tabla WHERE id = valor', 
'D.-ERASE FROM tabla WHERE id = valor', 
'A', 'El comando correcto es "DELETE FROM tabla WHERE id = valor".'),
(3, 1, '¿Qué comando se usa para hacer una copia de seguridad de una base de datos en SQL?', NULL, NULL, 
'A.-BACKUP DATABASE nombre', 
'B.-EXPORT DATABASE nombre', 
'C.-SAVE DATABASE nombre', 
'D.-DUMP DATABASE nombre', 
'A', 'El comando "BACKUP DATABASE nombre" se usa para crear una copia de seguridad en SQL.'),
(3, 1, '¿Cuál es la estructura básica de una consulta SQL?', NULL, NULL, 
'A.-GET columna FROM tabla', 
'B.-SELECT columna FROM tabla', 
'C.-FETCH columna FROM tabla', 
'D.-SHOW columna FROM tabla', 
'B', 'La estructura básica de una consulta SQL es "SELECT columna FROM tabla".'),
(3, 1, '¿Qué hace la cláusula LIMIT en una consulta SQL?', NULL, NULL, 
'A.-Limita el número de registros devueltos', 
'B.-Ordena los registros de la consulta', 
'C.-Agrupa los datos en la consulta', 
'D.-Elimina registros duplicados', 
'A', 'La cláusula "LIMIT" restringe la cantidad de registros devueltos por una consulta SQL.'),
(3, 1, '¿Cómo se combinan registros de dos tablas en SQL?', NULL, NULL, 
'A.-USING JOIN', 
'B.-COMBINE TABLES', 
'C.-MERGE TABLES', 
'D.-USING UNION', 
'D', 'El operador "UNION" combina los resultados de dos consultas SQL.'),
(3, 1, '¿Qué operador se usa para buscar un patrón de texto en SQL?', NULL, NULL, 
'A.-LIKE', 
'B.-FIND', 
'C.-MATCH', 
'D.-SEARCH', 
'A', 'El operador "LIKE" permite buscar patrones en columnas de texto en SQL.');

COMMIT;