package constantes;

public class QuerysTester {
	public static final String QUERY_ALL_FROM_PREGUNTAS_ID = "SELECT * FROM PREGUNTAS WHERE ID_PREGUNTA = ?";
	public static final String QUERY_COUNT_PREGUNTAS = "SELECT COUNT(*) AS TOTAL_PREGUNTAS FROM PREGUNTAS";
	public static final String QUERY_GET_TEMAS = "SELECT * FROM TEMA";
	public static final String QUERY_GET_SUBTEMAS = "SELECT * FROM SUBTEMA";
	public static final String QUERY_GET_TOPICO = "SELECT * FROM TOPICO";
	public static final String QUERY_GET_SUBTEMA_ACTIVO = "SELECT * FROM PREGUNTAS WHERE ID_SUBTEMA_TOPICO IN \r\n"
			+ "(SELECT ID_SUBTEMA_TOPICO FROM SUBTEMA_TOPICO WHERE ID_SUBTEMA IN \r\n"
			+ "(SELECT ID_SUBTEMA FROM SUBTEMA WHERE ESTATUS = 'A'))";
}
