#***** 1.- INSERTS DE INFORMATICA*****--
#***** 1.1.- INSERTS DE INFORMATICA > JAVA*****--
#***** 1.1.1- INSERTS DE INFORMATICA > JAVA > SINTAXIS*****--
INSERT INTO PREGUNTAS (
ID_SUBTEMA_TOPICO,
ID_ORIGEN,
PREGUNTA,
IMAGEN,
RUTA_ARCHIVO,
RESPUESTA_A,
RESPUESTA_B,
RESPUESTA_C,
RESPUESTA_D,
RESPUESTA_CORRECTA,
EXPLICACION) VALUES 
(1,
1,
'¿Cuál de las siguientes opciones es una declaración válida de variable en Java?',
NULL,
NULL,
'A.-int numero = "10";',
'B.-double precio = 25.99;',
'C.-string nombre = "Java";',
'D.-booleano esValido = true;',
'B',
NULL),
(1,
1,
'¿Cuál de los siguientes modificadores de acceso permite que una variable o método solo sea accesible dentro de la misma clase?',
NULL,
NULL,
'A.-public',
'B.-protected',
'C.-private',
'D.-default',
'C',
NULL),
(1, 1, '¿Qué palabra clave se usa para declarar una constante en Java?', NULL, NULL, 
'A.-const', 
'B.-final', 
'C.-static', 
'D.-let', 
'B', 'En Java, la palabra clave "final" se usa para declarar constantes.'),
(1, 1, '¿Cuál es el tipo de dato predeterminado para números decimales en Java?', NULL, NULL, 
'A.-float', 
'B.-double', 
'C.-int', 
'D.-decimal', 
'B', 'El tipo de dato predeterminado para números decimales en Java es "double".'),
(1, 1, '¿Qué operador se usa para comparar si dos valores son iguales en Java?', NULL, NULL, 
'A.-==', 
'B.-=', 
'C.-equals()', 
'D.-!=', 
'A', 'El operador "==" se usa para comparar valores primitivos en Java. Para objetos, se usa equals().'),
(1, 1, '¿Cuál de los siguientes no es un tipo de dato primitivo en Java?', NULL, NULL, 
'A.-int', 
'B.-String', 
'C.-double', 
'D.-boolean', 
'B', 'String no es un tipo de dato primitivo, es una clase en Java.'),
(1, 1, '¿Cómo se declara un array de enteros en Java?', NULL, NULL, 
'A.-int array[] = new int[5];', 
'B.-array<int> = new int[5];', 
'C.-int[] array = new int(5);', 
'D.-array[] int = new int[5];', 
'A', 'La forma correcta de declarar un array en Java es "int array[] = new int[5];".'),
(1, 1, '¿Cuál es el resultado de la operación 10 / 3 en Java si ambos son enteros?', NULL, NULL, 
'A.-3.33', 
'B.-3', 
'C.-4', 
'D.-Error', 
'B', 'En Java, la división entre enteros devuelve un entero, por lo que 10 / 3 es 3.'),
(1, 1, '¿Qué estructura se usa para manejar excepciones en Java?', NULL, NULL, 
'A.-if-else', 
'B.-switch-case', 
'C.-try-catch', 
'D.-for-each', 
'C', 'El bloque try-catch se usa para manejar excepciones en Java.'),
(1, 1, '¿Cuál de las siguientes opciones es un bucle en Java?', NULL, NULL, 
'A.-loop()', 
'B.-foreach()', 
'C.-do-while', 
'D.-if-else', 
'C', 'do-while es un bucle en Java que se ejecuta al menos una vez antes de evaluar la condición.'),
(1, 1, '¿Cuál es la función principal de la palabra clave "this" en Java?', NULL, NULL, 
'A.-Referenciar la superclase', 
'B.-Referenciar la propia instancia de la clase', 
'C.-Indicar una variable global', 
'D.-Acceder a métodos estáticos', 
'B', 'La palabra clave "this" en Java se usa para referenciar la instancia actual de la clase.'),
(1, 1, '¿Qué palabra clave se usa para heredar una clase en Java?', NULL, NULL, 
'A.-implements', 
'B.-inherits', 
'C.-extends', 
'D.-override', 
'C', 'Para heredar una clase en Java se usa "extends".'),
(1, 1, '¿Qué modificador de acceso permite que un método sea accesible desde cualquier parte del programa?', NULL, NULL, 
'A.-private', 
'B.-protected', 
'C.-default', 
'D.-public', 
'D', 'El modificador "public" permite que un método sea accesible desde cualquier parte del programa.'),
(1, 1, '¿Qué pasa si un método tiene el mismo nombre pero diferente número de parámetros?', NULL, NULL, 
'A.-Error de compilación', 
'B.-Sobrecarga de métodos', 
'C.-Sobrescritura de métodos', 
'D.-No es permitido en Java', 
'B', 'Se llama sobrecarga de métodos (method overloading), donde un método tiene el mismo nombre pero diferentes parámetros.'),
(1, 1, '¿Cómo se llama el proceso de convertir un objeto de una subclase a su superclase?', NULL, NULL, 
'A.-Downcasting', 
'B.-Upcasting', 
'C.-Polimorfismo', 
'D.-Instanciación', 
'B', 'Upcasting es el proceso de convertir un objeto de una subclase a su superclase en Java.'),
(1, 1, '¿Cuál es el valor predeterminado de un atributo de instancia de tipo int en Java?', NULL, NULL, 
'A.-null', 
'B.-0', 
'C.-1', 
'D.-No tiene valor por defecto', 
'B', 'Los atributos de tipo int en Java tienen un valor predeterminado de 0.'),
(1, 1, '¿Cuál de los siguientes no es un operador lógico en Java?', NULL, NULL, 
'A.-&&', 
'B.-||', 
'C.-!', 
'D.-%%', 
'D', 'El operador "%%" no existe en Java. Los operadores lógicos válidos son &&, || y !.'),
(1, 1, '¿Qué tipo de dato devuelve un método con la firma "public void metodo()"?', NULL, NULL, 
'A.-int', 
'B.-void', 
'C.-null', 
'D.-No devuelve nada', 
'B', 'El tipo "void" indica que el método no devuelve ningún valor.'),
(1, 1, '¿Qué palabra clave se usa para definir una interfaz en Java?', NULL, NULL, 
'A.-abstract', 
'B.-class', 
'C.-interface', 
'D.-implements', 
'C', 'La palabra clave "interface" se usa para definir interfaces en Java.'),
(1, 1, '¿Cuál es la salida de System.out.println(2 + "3"); en Java?', NULL, NULL, 
'A.-5', 
'B.-23', 
'C.-Error de compilación', 
'D.-Ninguna de las anteriores', 
'B', 'En Java, si se concatena un número con un string, el número se convierte en string.'),
(1, 1, '¿Qué método se ejecuta automáticamente cuando se instancia una clase en Java?', NULL, NULL, 
'A.-run()', 
'B.-start()', 
'C.-constructor', 
'D.-initialize()', 
'C', 'El constructor es el método que se ejecuta automáticamente al instanciar una clase en Java.');