SELECT ST.ID_SUBTEMA_TOPICO,ST.ID_SUBTEMA,ST.ID_TOPICO,
SU.NOMBRE_SUBTEMA, TOP.NOMBRE_TOPICO
FROM SUBTEMA_TOPICO ST
JOIN SUBTEMA SU ON ST.ID_SUBTEMA = SU.ID_SUBTEMA
JOIN TOPICO TOP ON ST.ID_TOPICO = TOP.ID_TOPICO;



#SCRUM
SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'DAILY';

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'HISTORIAS DE USUARIO'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA_TOPICO,ID_SUBTEMA,ID_TOPICO) VALUES (7,
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'DAILY'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'FASES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'CEREMONIAS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'EPICAS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'GRAFICAS DE SCRUM'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SCRUM'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'ARTEACTOS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'ESTRUCTURAS DE CONTROL'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'BUCLES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'TIPOS DE DATOS Y VARIABLES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'CURSORES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'PROCEDIMIENTOS Y FUNCIONES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'CONSULTAS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'MANIPULACION DE TABLAS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'CLAUSULAS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'TRANSACCIONES Y CONTROL DE CONCURRENCIA'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'PAQUETES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'TRIGGERS'));


INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'MANEJO DE EVENTOS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'EXCEPCIONES'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'CONSULTAS DINAMICAS'));

INSERT INTO SUBTEMA_TOPICO (ID_SUBTEMA,ID_TOPICO) VALUES (
(SELECT ID_SUBTEMA FROM SUBTEMA WHERE NOMBRE_SUBTEMA = 'SQL'),
(SELECT ID_TOPICO FROM TOPICO WHERE NOMBRE_TOPICO = 'VISTAS MATERIALIZADAS'));